/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.5, Date: 06-May-2016.
 */
#ifndef CONSTANT_DEFINITIONS_H
#define CONSTANT_DEFINITIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"

/**
 * Header file for ASN.1 module Constant-definitions
 */
/* Value definitions */

#define ASN1V_utran_hiPDSCHidentities 64
#define ASN1V_utran_hiPUSCHidentities 64
#define ASN1V_utran_hiRM 256
#define ASN1V_utran_maxAC 16
#define ASN1V_utran_maxAdditionalMeas 4
#define ASN1V_utran_maxAddPos 8
#define ASN1V_utran_maxASC 8
#define ASN1V_utran_maxASCmap 7
#define ASN1V_utran_maxASCpersist 6
#define ASN1V_utran_maxBeacons 64
#define ASN1V_utran_maxBTs 32
#define ASN1V_utran_maxCCTrCH 8
#define ASN1V_utran_maxCellMeas 32
#define ASN1V_utran_maxCellMeas_ext 80
#define ASN1V_utran_maxCellMeas_ext2 48
#define ASN1V_utran_maxCellMeasOnSecULFreq 32
#define ASN1V_utran_maxCellMeas_1 31
#define ASN1V_utran_maxCellMeas_ext_1 79
#define ASN1V_utran_maxCellMeasOnSecULFreq_1 31
#define ASN1V_utran_maxCNdomains 4
#define ASN1V_utran_maxCommonHRNTI 4
#define ASN1V_utran_maxCommonQueueID 2
#define ASN1V_utran_maxCPCHsets 16
#define ASN1V_utran_maxDedicatedCSGFreq 4
#define ASN1V_utran_maxDPCH_DLchan 8
#define ASN1V_utran_maxDPDCH_UL 6
#define ASN1V_utran_maxDRACclasses 8
#define ASN1V_utran_maxExcludedDetectedSetCells 64
#define ASN1V_utran_maxE_DCHMACdFlow 8
#define ASN1V_utran_maxE_DCHMACdFlow_1 7
#define ASN1V_utran_maxMultipleFrequencyBandsFDD 8
#define ASN1V_utran_maxMultipleFrequencyBandsEUTRA 8
#define ASN1V_utran_maxEUTRACellPerFreq 16
#define ASN1V_utran_maxEUTRATargetFreqs 8
#define ASN1V_utran_maxEDCHRL 4
#define ASN1V_utran_maxEDCHRL_1 3
#define ASN1V_utran_maxEDCHs 32
#define ASN1V_utran_maxEDCHs_1 31
#define ASN1V_utran_maxEDCHTxPattern_TDD128 4
#define ASN1V_utran_maxEDCHTxPattern_TDD128_1 3
#define ASN1V_utran_maxERNTIgroup 32
#define ASN1V_utran_maxERNTIperGroup 2
#define ASN1V_utran_maxERUCCH 256
#define ASN1V_utran_maxFACHPCH 8
#define ASN1V_utran_maxFreq 8
#define ASN1V_utran_maxFreqBandsEUTRA 16
#define ASN1V_utran_maxFreqBandsEUTRA_ext 48
#define ASN1V_utran_maxFreqBandsFDD 8
#define ASN1V_utran_maxFreqBandsFDD2 22
#define ASN1V_utran_maxFreqBandsFDD3 86
#define ASN1V_utran_maxFreqBandsFDD_ext 15
#define ASN1V_utran_maxFreqBandsFDD_ext2 64
#define ASN1V_utran_maxFreqBandsFDD_ext3 78
#define ASN1V_utran_maxFreqBandsIndicatorSupport 2
#define ASN1V_utran_maxFreqBandsTDD 4
#define ASN1V_utran_maxFreqBandsTDD_ext 16
#define ASN1V_utran_maxFreqBandsGSM 16
#define ASN1V_utran_maxFreqMeasWithoutCM 2
#define ASN1V_utran_maxGANSS 8
#define ASN1V_utran_maxGANSS_1 7
#define ASN1V_utran_maxGANSSSat 64
#define ASN1V_utran_maxGANSSSat_1 63
#define ASN1V_utran_maxGERAN_SI 8
#define ASN1V_utran_maxGSMTargetCells 32
#define ASN1V_utran_maxHNBNameSize 48
#define ASN1V_utran_maxHProcesses 8
#define ASN1V_utran_maxHS_SCCHLessTrBlk 4
#define ASN1V_utran_maxHSDSCHTBIndex 64
#define ASN1V_utran_maxHSDSCHTBIndex_tdd384 512
#define ASN1V_utran_maxHSSCCHs 4
#define ASN1V_utran_maxHSSCCHs_1 3
#define ASN1V_utran_maxHSSICH_TDD128 4
#define ASN1V_utran_maxHSSICH_TDD128_1 3
#define ASN1V_utran_maxIGPInfo 320
#define ASN1V_utran_maxInterSysMessages 4
#define ASN1V_utran_maxLoCHperRLC 2
#define ASN1V_utran_maxLoggedMeasReport 128
#define ASN1V_utran_maxMAC_d_PDUsizes 8
#define ASN1V_utran_maxMBMS_CommonCCTrCh 32
#define ASN1V_utran_maxMBMS_CommonPhyCh 32
#define ASN1V_utran_maxMBMS_CommonRB 32
#define ASN1V_utran_maxMBMS_CommonTrCh 32
#define ASN1V_utran_maxMBMS_Freq 4
#define ASN1V_utran_maxMBMS_L1CP 4
#define ASN1V_utran_maxMBMSservCount 8
#define ASN1V_utran_maxMBMSservModif 32
#define ASN1V_utran_maxMBMSservSched 16
#define ASN1V_utran_maxMBMSservSelect 8
#define ASN1V_utran_maxMBMSservUnmodif 64
#define ASN1V_utran_maxMBMSTransmis 4
#define ASN1V_utran_maxMBSFNClusters 16
#define ASN1V_utran_maxMeasCSGRange 4
#define ASN1V_utran_maxMeasEvent 8
#define ASN1V_utran_maxMeasEventOnSecULFreq 8
#define ASN1V_utran_maxMeasIdentity 32
#define ASN1V_utran_maxMeasIntervals 3
#define ASN1V_utran_maxMeasOccasionPattern 5
#define ASN1V_utran_maxMeasOccasionPattern_1 4
#define ASN1V_utran_maxMeasParEvent 2
#define ASN1V_utran_maxNonContiguousMultiCellCombinations 3
#define ASN1V_utran_maxNumAccessGroups 16
#define ASN1V_utran_maxNumAcdcCategory 16
#define ASN1V_utran_maxNumCDMA2000Freqs 8
#define ASN1V_utran_maxNumE_AGCH 4
#define ASN1V_utran_maxNumE_HICH 4
#define ASN1V_utran_maxNumEUTRAFreqs 8
#define ASN1V_utran_maxNumEUTRAFreqs_FACH 4
#define ASN1V_utran_maxNumEUTRAFreqs_FACH_ext 8
#define ASN1V_utran_maxNumGSMCellGroup 16
#define ASN1V_utran_maxNumGSMFreqRanges 32
#define ASN1V_utran_maxNumFDDFreqs 8
#define ASN1V_utran_maxNumANRLoggedItems 4
#define ASN1V_utran_maxnumLoggedMeas 8
#define ASN1V_utran_maxNumMDTPLMN 15
#define ASN1V_utran_maxNumTDDFreqs 8
#define ASN1V_utran_maxNoOfMeas 16
#define ASN1V_utran_maxOtherRAT 15
#define ASN1V_utran_maxOtherRAT_16 16
#define ASN1V_utran_maxPage1 8
#define ASN1V_utran_maxPCPCH_APsig 16
#define ASN1V_utran_maxPCPCH_APsubCh 12
#define ASN1V_utran_maxPCPCH_CDsig 16
#define ASN1V_utran_maxPCPCH_CDsubCh 12
#define ASN1V_utran_maxPCPCH_SF 7
#define ASN1V_utran_maxPCPCHs 64
#define ASN1V_utran_maxPDCPAlgoType 8
#define ASN1V_utran_maxPDSCH 8
#define ASN1V_utran_maxPDSCH_TFCIgroups 256
#define ASN1V_utran_maxPRACH 16
#define ASN1V_utran_maxPRACH_EUL 4
#define ASN1V_utran_maxPRACH_FPACH 8
#define ASN1V_utran_maxPredefConfig 16
#define ASN1V_utran_maxOtherStateConfig 4
#define ASN1V_utran_maxOtherStateConfig_1 3
#define ASN1V_utran_maxPrio 8
#define ASN1V_utran_maxPrio_1 7
#define ASN1V_utran_maxPrio_ext 16
#define ASN1V_utran_maxPUSCH 8
#define ASN1V_utran_maxQueueIDs 8
#define ASN1V_utran_maxRABsetup 16
#define ASN1V_utran_maxRAT 16
#define ASN1V_utran_maxRB 32
#define ASN1V_utran_maxRBallRABs 27
#define ASN1V_utran_maxRBMuxOptions 8
#define ASN1V_utran_maxRBperRAB 8
#define ASN1V_utran_maxRBperTrCh 16
#define ASN1V_utran_maxReportedEUTRACellPerFreq 4
#define ASN1V_utran_maxReportedEUTRAFreqs 4
#define ASN1V_utran_maxReportedEUTRAFreqs_ext 8
#define ASN1V_utran_maxReportedGSMCells 8
#define ASN1V_utran_maxRetrievConfig 8
#define ASN1V_utran_maxRetrievConfig_1 7
#define ASN1V_utran_maxRL 8
#define ASN1V_utran_maxRL_1 7
#define ASN1V_utran_maxRLCPDUsizePerLogChan 32
#define ASN1V_utran_maxRMPfrequencies 8
#define ASN1V_utran_maxRFC3095_CID 16384
#define ASN1V_utran_maxROHC_PacketSizes_r4 16
#define ASN1V_utran_maxROHC_Profile_r4 8
#define ASN1V_utran_maxRxPatternForHSDSCH_TDD128 4
#define ASN1V_utran_maxRxPatternForHSDSCH_TDD128_1 3
#define ASN1V_utran_maxSat 16
#define ASN1V_utran_maxSatClockModels 4
#define ASN1V_utran_maxSCCPCH 16
#define ASN1V_utran_maxSgnType 8
#define ASN1V_utran_maxSIB 32
#define ASN1V_utran_maxSIB2 64
#define ASN1V_utran_maxSIB_FACH 8
#define ASN1V_utran_maxSIBperMsg 16
#define ASN1V_utran_maxSIrequest 4
#define ASN1V_utran_maxSRBsetup 8
#define ASN1V_utran_maxSystemCapability 16
#define ASN1V_utran_maxTDD128Carrier 6
#define ASN1V_utran_maxTDD128Carrier_1 5
#define ASN1V_utran_maxTbsForHSDSCH_TDD128 4
#define ASN1V_utran_maxTbsForHSDSCH_TDD128_1 3
#define ASN1V_utran_maxTF 32
#define ASN1V_utran_maxTF_CPCH 16
#define ASN1V_utran_maxTFC 1024
#define ASN1V_utran_maxTFCsub 1024
#define ASN1V_utran_maxTFCI_2_Combs 512
#define ASN1V_utran_maxTGPS 6
#define ASN1V_utran_maxTrCH 32
#define ASN1V_utran_maxTrCHConcat 3
#define ASN1V_utran_maxTrCHpreconf 32
#define ASN1V_utran_maxTS 14
#define ASN1V_utran_maxTS_1 13
#define ASN1V_utran_maxTS_2 12
#define ASN1V_utran_maxTS_LCR 6
#define ASN1V_utran_maxTS_LCR_1 5
#define ASN1V_utran_maxURA 8
#define ASN1V_utran_maxURNTI_Group 8
#define ASN1V_utran_maxWLANID 16
#define ASN1V_utran_maxWLANs 64

#ifdef __cplusplus
}
#endif

#endif
