/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef OAM_ENB_MIB_TABLES_H
#define OAM_ENB_MIB_TABLES_H

#include<oam_snmp_interface.h>


/*
 * column number definitions for table plmnListTable 
 */
#define COLUMN_PLMNLISTTBLINDEX		                                 1
#define COLUMN_PLMNLISTTBLENABLE		                             2
#define COLUMN_PLMNLISTTBLISPRIMARY		                             3
#define COLUMN_PLMNLISTTBLPLMNID		                             4
#define COLUMN_PLMNLISTTBLCELLRESERVEDFOROPERATORUSE		         5

/*
 * column number definitions for table qoSTable 
 */
#define COLUMN_QOSTBLINDEX		                                     1
#define COLUMN_QOSTBLQCI		                                     2
#define COLUMN_QOSTBLTYPE		                                     3
#define COLUMN_QOSTBLPRIORITY	                                   	 4
#define COLUMN_QOSTBLPACKETDELAYBUDGET		                         5

/*
 * column number definitions for table sfConfigListTable 
 */
#define COLUMN_SFCONFIGLISTTBLINDEX		1
#define COLUMN_SFCONFIGLISTTBLSYNCSTRATUMID		2
#define COLUMN_SFCONFIGLISTTBLRADIOFRAMEALLOCATIONPERIOD		3
#define COLUMN_SFCONFIGLISTTBLRADIOFRAMEALLOCATIONOFFSET		4
#define COLUMN_SFCONFIGLISTTBLRADIOFRAMEALLOCATIONSIZE		5
#define COLUMN_SFCONFIGLISTTBLSUBFRAMEALLOCATIONS		6

/*
 * column number definitions for table carrierTable 
 */
#define COLUMN_CARRIERTBLINDEX		                                 1
#define COLUMN_CARRIERTBLEUTRACARRIERARFCN		                     2
#define COLUMN_CARRIERTBLQOFFSETFREQ		                         3
#define COLUMN_CARRIERTBLQRXLEVMINSIB5		                         4
#define COLUMN_CARRIERTBLPMAX		                                 5
#define COLUMN_CARRIERTBLTRESELECTIONEUTRA		                     6
#define COLUMN_CARRIERTBLTRESELECTIONEUTRASFMEDIUM		             7
#define COLUMN_CARRIERTBLTRESELECTIONEUTRASFHIGH		             8
#define COLUMN_CARRIERTBLTHRESHXHIGH		                         9
#define COLUMN_CARRIERTBLTHRESHXLOW		                            10
#define COLUMN_CARRIERTBLCELLRESELECTIONPRIORITY		            11

/*
 * column number definitions for table utranFDDFreqTable 
 */
#define COLUMN_UTRANFDDFREQTBLINDEX		                             1
#define COLUMN_UTRANFDDFREQTBLUTRACARRIERARFCN		                 2
#define COLUMN_UTRANFDDFREQTBLQRXLEVMIN		                         3
#define COLUMN_UTRANFDDFREQTBLQQUALMIN		                         4
#define COLUMN_UTRANFDDFREQTBLCELLRESELECTIONPRIORITY		         5
#define COLUMN_UTRANFDDFREQTBLTHRESHXHIGH		                     6
#define COLUMN_UTRANFDDFREQTBLTHRESHXLOW		                     7
#define COLUMN_UTRANFDDFREQTBLPMAXUTRA		                         8

/*
 * column number definitions for table geranFreqGroupTable 
 */
#define COLUMN_GERANFREQGROUPTBLINDEX		                         1
#define COLUMN_GERANFREQGROUPTBLQRXLEVMIN	 	                     2
#define COLUMN_GERANFREQGROUPTBLCELLRESELECTIONPRIORITY		         3
#define COLUMN_GERANFREQGROUPTBLTHRESHXHIGH		                     4
#define COLUMN_GERANFREQGROUPTBLTHRESHXLOW		                     5

/*
 * column number definitions for table neighborListLTECellTable 
 */
#define COLUMN_NEIGHBORLISTLTECELLTBLINDEX		                     1
#define COLUMN_NEIGHBORLISTLTECELLTBLPLMNID		                     2
#define COLUMN_NEIGHBORLISTLTECELLTBLCID		                     3
#define COLUMN_NEIGHBORLISTLTECELLTBLEUTRACARRIERARFCN		         4
#define COLUMN_NEIGHBORLISTLTECELLTBLPHYCELLID		                 5
#define COLUMN_NEIGHBORLISTLTECELLTBLQOFFSET		                 6
#define COLUMN_NEIGHBORLISTLTECELLTBLCIO		                     7
#define COLUMN_NEIGHBORLISTLTECELLTBLBLACKLISTED		             8

/*
 * column number definitions for table neighborListUMTSTable 
 */
#define COLUMN_NEIGHBORLISTUMTSTBLINDEX		                         1
#define COLUMN_NEIGHBORLISTUMTSTBLPLMNID		                     2
#define COLUMN_NEIGHBORLISTUMTSTBLRNCID		                         3
#define COLUMN_NEIGHBORLISTUMTSTBLCID		                         4
#define COLUMN_NEIGHBORLISTUMTSTBLLAC		                         5
#define COLUMN_NEIGHBORLISTUMTSTBLRAC		                         6
#define COLUMN_NEIGHBORLISTUMTSTBLUARFCNDL		                     7

/*
 * column number definitions for table neighborListInUseLTECellTable 
 */
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLINDEX		                 1
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLPLMNID		             2
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLCID		                 3
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLEUTRACARRIERARFCN		     4
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLPHYCELLID		             5
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLQOFFSET		             6
#define COLUMN_NEIGHBORLISTINUSELTECELLTBLBLACKLISTED		         7

/*
 * column number definitions for table neighborListInUseUMTSTable 
 */
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLINDEX		                 1
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLPLMNID		                 2
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLRNCID		                 3
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLCID		                     4
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLLAC		                     5
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLRAC		                     6
#define COLUMN_NEIGHBORLISTINUSEUMTSTBLUARFCNDL		                 7

/*
 * column number definitions for table currentAlarmTable 
 */
#define COLUMN_CURRENTALARMTBLINDEX		                             1
#define COLUMN_CURRENTALARMTBLALARMIDENTIFIER		                 2
#define COLUMN_CURRENTALARMTBLRAISEDTIME		                     3
#define COLUMN_CURRENTALARMTBLCHANGEDTIME		                     4
#define COLUMN_CURRENTALARMTBLMANAGEDOBJECTINSTANCE		             5
#define COLUMN_CURRENTALARMTBLEVENTTYPE		                         6
#define COLUMN_CURRENTALARMTBLPROBABLECAUSE	 	                     7
#define COLUMN_CURRENTALARMTBLSPECIFICPROBLEM		                 8
#define COLUMN_CURRENTALARMTBLPERCEIVEDSEVERITY		                 9
#define COLUMN_CURRENTALARMTBLADDITIONALTEXT		                10
#define COLUMN_CURRENTALARMTBLADDITIONALINFORMATION		            11

/*
 * column number definitions for table supportedAlarmTable 
 */
#define COLUMN_SUPPORTEDALARMTBLINDEX		                         1
#define COLUMN_SUPPORTEDALARMTBLEVENTTYPE		                     2
#define COLUMN_SUPPORTEDALARMTBLPROBABLECAUSE		                 3
#define COLUMN_SUPPORTEDALARMTBLSPECIFICPROBLEM		                 4
#define COLUMN_SUPPORTEDALARMTBLPERCEIVEDSEVERITY		             5
#define COLUMN_SUPPORTEDALARMTBLREPORTINGMECHANISM		             6

/*
 * column number definitions for table historyEventTable 
 */
#define COLUMN_HISTORYEVENTTBLINDEX		                             1
#define COLUMN_HISTORYEVENTTBLEVENTTIME		                         2
#define COLUMN_HISTORYEVENTTBLALARMIDENTIFIER		                 3
#define COLUMN_HISTORYEVENTTBLNOTIFICATIONTYPE		                 4
#define COLUMN_HISTORYEVENTTBLMANAGEDOBJECTINSTANCE		             5
#define COLUMN_HISTORYEVENTTBLEVENTTYPE		                         6
#define COLUMN_HISTORYEVENTTBLPROBABLECAUSE		                     7
#define COLUMN_HISTORYEVENTTBLSPECIFICPROBLEM		                 8
#define COLUMN_HISTORYEVENTTBLPERCEIVEDSEVERITY		                 9
#define COLUMN_HISTORYEVENTTBLADDITIONALTEXT		                10
#define COLUMN_HISTORYEVENTTBLADDITIONALINFORMATION		            11

/*
 * column number definitions for table expeditedEventTable 
 */
#define COLUMN_EXPEDITEDEVENTTBLINDEX		                         1
#define COLUMN_EXPEDITEDEVENTTBLEVENTTIME		                     2
#define COLUMN_EXPEDITEDEVENTTBLALARMIDENTIFIER		                 3
#define COLUMN_EXPEDITEDEVENTTBLNOTIFICATIONTYPE		             4
#define COLUMN_EXPEDITEDEVENTTBLMANAGEDOBJECTINSTANCE		         5
#define COLUMN_EXPEDITEDEVENTTBLEVENTTYPE		                     6
#define COLUMN_EXPEDITEDEVENTTBLPROBABLECAUSE		                 7
#define COLUMN_EXPEDITEDEVENTTBLSPECIFICPROBLEM		                 8
#define COLUMN_EXPEDITEDEVENTTBLPERCEIVEDSEVERITY		             9
#define COLUMN_EXPEDITEDEVENTTBLADDITIONALTEXT		                10
#define COLUMN_EXPEDITEDEVENTTBLADDITIONALINFORMATION		        11

/*
 * column number definitions for table queuedEventTable 
 */
#define COLUMN_QUEUEDEVENTTBLINDEX		                             1
#define COLUMN_QUEUEDEVENTTBLEVENTTIME		                         2
#define COLUMN_QUEUEDEVENTTBLALARMIDENTIFIER		                 3
#define COLUMN_QUEUEDEVENTTBLNOTIFICATIONTYPE		                 4
#define COLUMN_QUEUEDEVENTTBLMANAGEDOBJECTINSTANCE		             5
#define COLUMN_QUEUEDEVENTTBLEVENTTYPE		                         6
#define COLUMN_QUEUEDEVENTTBLPROBABLECAUSE		                     7
#define COLUMN_QUEUEDEVENTTBLSPECIFICPROBLEM		                 8
#define COLUMN_QUEUEDEVENTTBLPERCEIVEDSEVERITY		                 9
#define COLUMN_QUEUEDEVENTTBLADDITIONALTEXT		                    10
#define COLUMN_QUEUEDEVENTTBLADDITIONALINFORMATION		            11



/** User-defined data access functions for data in table plmnListTable */
/** row level accessors */
Netsnmp_First_Data_Point plmnListTable_get_first_data_point;
Netsnmp_Next_Data_Point plmnListTable_get_next_data_point;

/** User-defined data access functions for data in table qoSTable */
/** row level accessors */
Netsnmp_First_Data_Point qoSTable_get_first_data_point;
Netsnmp_Next_Data_Point qoSTable_get_next_data_point;

/** User-defined data access functions for data in table sfConfigListTable */
/** row level accessors */
Netsnmp_First_Data_Point sfConfigListTable_get_first_data_point;
Netsnmp_Next_Data_Point sfConfigListTable_get_next_data_point;

/** User-defined data access functions for data in table carrierTable */
/** row level accessors */
Netsnmp_First_Data_Point carrierTable_get_first_data_point;
Netsnmp_Next_Data_Point carrierTable_get_next_data_point;

/** User-defined data access functions for data in table utranFDDFreqTable */
/** row level accessors */
Netsnmp_First_Data_Point utranFDDFreqTable_get_first_data_point;
Netsnmp_Next_Data_Point utranFDDFreqTable_get_next_data_point;

/** User-defined data access functions for data in table geranFreqGroupTable */
/** row level accessors */
Netsnmp_First_Data_Point geranFreqGroupTable_get_first_data_point;
Netsnmp_Next_Data_Point geranFreqGroupTable_get_next_data_point;

/** User-defined data access functions for data in table neighborListLTECellTable */
/** row level accessors */
Netsnmp_First_Data_Point neighborListLTECellTable_get_first_data_point;
Netsnmp_Next_Data_Point neighborListLTECellTable_get_next_data_point;

/** User-defined data access functions for data in table neighborListUMTSTable */
/** row level accessors */
Netsnmp_First_Data_Point neighborListUMTSTable_get_first_data_point;
Netsnmp_Next_Data_Point neighborListUMTSTable_get_next_data_point;

/** User-defined data access functions for data in table neighborListInUseLTECellTable */
/** row level accessors */
Netsnmp_First_Data_Point
    neighborListInUseLTECellTable_get_first_data_point;
Netsnmp_Next_Data_Point neighborListInUseLTECellTable_get_next_data_point;

/** User-defined data access functions for data in table neighborListInUseUMTSTable */
/** row level accessors */
Netsnmp_First_Data_Point neighborListInUseUMTSTable_get_first_data_point;
Netsnmp_Next_Data_Point neighborListInUseUMTSTable_get_next_data_point;

/** User-defined data access functions for data in table currentAlarmTable */
/** row level accessors */
Netsnmp_First_Data_Point currentAlarmTable_get_first_data_point;
Netsnmp_Next_Data_Point currentAlarmTable_get_next_data_point;

/** User-defined data access functions for data in table supportedAlarmTable */
/** row level accessors */
Netsnmp_First_Data_Point supportedAlarmTable_get_first_data_point;
Netsnmp_Next_Data_Point supportedAlarmTable_get_next_data_point;

/** User-defined data access functions for data in table historyEventTable */
/** row level accessors */
Netsnmp_First_Data_Point historyEventTable_get_first_data_point;
Netsnmp_Next_Data_Point historyEventTable_get_next_data_point;

/** User-defined data access functions for data in table expeditedEventTable */
/** row level accessors */
Netsnmp_First_Data_Point expeditedEventTable_get_first_data_point;
Netsnmp_Next_Data_Point expeditedEventTable_get_next_data_point;

/** User-defined data access functions for data in table queuedEventTable */
/** row level accessors */
Netsnmp_First_Data_Point queuedEventTable_get_first_data_point;
Netsnmp_Next_Data_Point queuedEventTable_get_next_data_point;


    /*
     * function declarations 
     */
    void            init_oam_enb_mib_tables(void);
     void            initialize_table_plmnListTable(void);
     Netsnmp_Node_Handler plmnListTable_handler;

     void            initialize_table_qoSTable(void);
     Netsnmp_Node_Handler qoSTable_handler;

     void            initialize_table_sfConfigListTable(void);
     Netsnmp_Node_Handler sfConfigListTable_handler;

     void            initialize_table_carrierTable(void);
     Netsnmp_Node_Handler carrierTable_handler;

     void            initialize_table_utranFDDFreqTable(void);
     Netsnmp_Node_Handler utranFDDFreqTable_handler;

     void            initialize_table_geranFreqGroupTable(void);
     Netsnmp_Node_Handler geranFreqGroupTable_handler;

     void            initialize_table_neighborListLTECellTable(void);
     Netsnmp_Node_Handler neighborListLTECellTable_handler;

     void            initialize_table_neighborListUMTSTable(void);
     Netsnmp_Node_Handler neighborListUMTSTable_handler;

     void            initialize_table_neighborListInUseLTECellTable(void);
     Netsnmp_Node_Handler neighborListInUseLTECellTable_handler;

     void            initialize_table_neighborListInUseUMTSTable(void);
     Netsnmp_Node_Handler neighborListInUseUMTSTable_handler;

     void            initialize_table_currentAlarmTable(void);
     Netsnmp_Node_Handler currentAlarmTable_handler;

     void            initialize_table_supportedAlarmTable(void);
     Netsnmp_Node_Handler supportedAlarmTable_handler;

     void            initialize_table_historyEventTable(void);
     Netsnmp_Node_Handler historyEventTable_handler;

     void            initialize_table_expeditedEventTable(void);
     Netsnmp_Node_Handler expeditedEventTable_handler;

     void            initialize_table_queuedEventTable(void);
     Netsnmp_Node_Handler queuedEventTable_handler;


#define     SNMP_OAM_MAX_PLMNLIST_TABLE_ENTRIES                       6
#define     SNMP_OAM_MAX_QOS_TABLE_ENTRIES                            9
#define     SNMP_OAM_MAX_SFCONFIGLIST_TABLE_ENTRIES                   8
#define     SNMP_OAM_MAX_CARRIER_TABLE_ENTRIES                       12
#define     SNMP_OAM_MAX_UTRANFDDFREQ_TABLE_ENTRIES                  12
#define     SNMP_OAM_MAX_GERANFREQGROUP_TABLE_ENTRIES                16
#define     SNMP_OAM_MAX_NEIGHBORLISTLTECELL_TABLE_ENTRIES           32
#define     SNMP_OAM_MAX_NEIGHBORLISTUMTS_TABLE_ENTRIES              32
#define     SNMP_OAM_MAX_NEIGHBORLISTINUSELTECELL_TABLE_ENTRIES      32
#define     SNMP_OAM_MAX_NEIGHBORLISTINUSEUMTS_TABLE_ENTRIES         32
#define     SNMP_OAM_MAX_CURRENTALARM_TABLE_ENTRIES                 100
#define     SNMP_OAM_MAX_SUPPORTEDALARM_TABLE_ENTRIES               200
#define     SNMP_OAM_MAX_HISTORYEVENT_TABLE_ENTRIES                 200
#define     SNMP_OAM_MAX_EXPEDITEDEVENT_TABLE_ENTRIES               100
#define     SNMP_OAM_MAX_QUEUEDEVENT_TABLE_ENTRIES                  100

#define     PLMNID_MAX_LEN                                            7

#define     PLMNLIST_TBL_PARAM_START_IDX                  OID_PARAM_260
#define     SFCONFIGLIST_TBL_PARAM_START_IDX              OID_PARAM_392
#define     QOS_TBL_PARAM_START_IDX                       OID_PARAM_265
#define     CARRIER_TBL_PARAM_START_IDX                   OID_PARAM_270
#define     UTRANFDDFREQ_TBL_PARAM_START_IDX              OID_PARAM_281
#define     GERANFREQGROUP_TBL_PARAM_START_IDX            OID_PARAM_289
#define     NEIGHBORLISTLTECELL_TBL_PARAM_START_IDX       OID_PARAM_294
#define     NEIGHBORLISTUMTS_TBL_PARAM_START_IDX          OID_PARAM_302
#define     NEIGHBORLISTINUSELTECELL_TBL_PARAM_START_IDX  OID_PARAM_309
#define     NEIGHBORLISTINUSEUMTS_TBL_PARAM_START_IDX     OID_PARAM_316
#define     CURRENTALARM_TBL_PARAM_START_IDX              OID_PARAM_323
#define     SUPPORTEDALARM_TBL_PARAM_START_IDX            OID_PARAM_334
#define     HISTORYEVENT_TBL_PARAM_START_IDX              OID_PARAM_340
#define     EXPEDITEDEVENT_TBL_PARAM_START_IDX            OID_PARAM_351
#define     QUEUEDEVENT_TBL_PARAM_START_IDX               OID_PARAM_362


typedef enum __snmp_oam_table_type_et {
    PLMNLIST_TBL_TYPE,
    QOS_TBL_TYPE,
    SFCONFIGLIST_TBL_TYPE,
    CARRIER_TBL_TYPE,
    UTRANFDDFREQ_TBL_DATA,
    GERANFREQGROUP_TBL_TYPE,
    NEIGHBORLISTLTECELL_TBL_TYPE,
    NEIGHBORLISTUMTS_TBL_TYPE,
    NEIGHBORLISTINUSELTECELL_TBL_TYPE,
    NEIGHBORLISTINUSEUMTS_TBL_TYPE,
    CURRENTALARM_TBL_TYPE,
    SUPPORTEDALARM_TBL_TYPE,
    HISTORYEVENT_TBL_TYPE,
    EXPEDITEDEVENT_TBL_TYPE,
    QUEUEDEVENT_TBL_TYPE,
} snmp_oam_table_type_et;


unsigned
snmp_oam_get_table_size(snmp_oam_table_type_et type);

oam_mgmt_if_get_resp_t*
snmp_oam_get_row_data(snmp_oam_table_type_et type, unsigned index);

void*
snmp_oam_get_param_value(oam_mgmt_if_get_resp_t *p_data, int map_tbl_idx,
                         int data_type, size_t *size);


Netsnmp_Free_Data_Context snmp_oam_free_data_cntxt;

oam_mgmt_if_get_resp_t*
snmp_oam_get_first_row_data(snmp_oam_table_type_et tbl_type, unsigned *index,
                            unsigned *num_valid_index,
                            unsigned *num_rows, int max_index);


oam_mgmt_if_get_resp_t*
snmp_oam_get_next_row_data(snmp_oam_table_type_et tbl_type, unsigned *index,
                           unsigned *num_valid_index,
                           unsigned num_rows, int max_index);

void free_param_list(oam_mgmt_if_param_info_t  **p_head);
/* + SPR 17439 */
void deinitialize_table_data(void);
/* - SPR 17439 */


#endif /** OAM_ENB_MIB_TABLES_H */
