/****************************************************************************
 *File Name :oam_enb_mib_traps.h
 *
 *Description : This file contains functions to and definitions for SNMP trap
                code
 *              
 *
 *Revision Histroy:
 *
 *Date              Author      References   Comments
 *------------      --------    ----------   -------------
 *Aug 23, 2013      Vivek       OAM 2.3      Initial Version
 *Oct 08, 2013      Vivek       OAM 2.3      Increase in the length of
 *                                           event_time from 21 to 30 to 
 *                                           include the timezone information
 *
 *Copyright (c) 2013, Aricent Inc. All Rights Reserved
 ***************************************************************************/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef OAM_ENB_MIB_TRAPS_H
#define OAM_ENB_MIB_TRAPS_H

#include <lteTypes.h>


#define SNMP_OAM_IF_TRAP_OID_MAX_LEN    32


#define SNMP_OAM_IF_TRAP_PERCEIVED_SEV_MAX_LEN           16
#define SNMP_OAM_IF_TRAP_NOTIF_TYPE_MAX_LEN              16
#define SNMP_OAM_IF_TRAP_EVENT_TIME_MAX_LEN              30
#define SNMP_OAM_IF_TRAP_PROB_CAUSE_MAX_LEN              64
#define SNMP_OAM_IF_TRAP_EVENT_TYPE_MAX_LEN              64
#define SNMP_OAM_IF_TRAP_ID_MAX_LEN                      64
#define SNMP_OAM_IF_TRAP_SPEC_PROBLEM_MAX_LEN           128
#define SNMP_OAM_IF_TRAP_ADD_TEXT_MAX_LEN               256
#define SNMP_OAM_IF_TRAP_ADD_INFO_MAX_LEN               256
#define SNMP_OAM_IF_TRAP_MANAGED_OBJ_INST_MAX_LEN       512



typedef struct __snmp_oam_trap_param_t {
    Char8 trap_id[SNMP_OAM_IF_TRAP_ID_MAX_LEN];
    Char8 event_time[SNMP_OAM_IF_TRAP_EVENT_TIME_MAX_LEN];
    Char8 notif_type[SNMP_OAM_IF_TRAP_NOTIF_TYPE_MAX_LEN];
    Char8 managed_obj_inst[SNMP_OAM_IF_TRAP_MANAGED_OBJ_INST_MAX_LEN];
    Char8 event_type[SNMP_OAM_IF_TRAP_EVENT_TYPE_MAX_LEN];
    Char8 prob_cause[SNMP_OAM_IF_TRAP_PROB_CAUSE_MAX_LEN];
    Char8 spec_problem[SNMP_OAM_IF_TRAP_SPEC_PROBLEM_MAX_LEN];
    Char8 perceived_sev[SNMP_OAM_IF_TRAP_PERCEIVED_SEV_MAX_LEN];
    Char8 add_text[SNMP_OAM_IF_TRAP_ADD_TEXT_MAX_LEN];
    Char8 add_info[SNMP_OAM_IF_TRAP_ADD_INFO_MAX_LEN];
} snmp_oam_trap_param_t;

/*
 * function declarations 
 */

SInt32      snmp_oam_send_snmp_trap(snmp_oam_trap_param_t *trap_obj);
SInt16      snmp_oam_find_trap_oid(UInt16 trapid);

#endif                          /* OAM_ENB_MIB_TRAPS_H */
