/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.5, Date: 06-May-2016.
 */
#include "PDU-definitions.h"
#include "Constant-definitions.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_utran_UtranMobilityInformation_v690ext_IEs 
   (const char* name, const utran_UtranMobilityInformation_v690ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.primary_plmn_IdentityPresent) {
      asn1Print_utran_PLMN_Identity ("primary_plmn_Identity", &pvalue->
         primary_plmn_Identity);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_v860ext1_IEs 
   (const char* name, const utran_UTRANMobilityInformation_v860ext1_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UE_ConnTimersAndConstants_v860ext (
      "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions 
   (const char* name, const utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_v860ext1_IEs (
      "utranMobilityInformation_v860ext", &pvalue->
      utranMobilityInformation_v860ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UtranMobilityInformation_v690ext_IEs (
      "utranMobilityInformation_v690ext", &pvalue->
      utranMobilityInformation_v690ext);

   if (pvalue->m.v860NonCriticalExtentionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions_v860NonCriticalExtentions (
         "v860NonCriticalExtentions", &pvalue->v860NonCriticalExtentions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.utranMobilityInformation_r3_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformation_r3_add_ext", pvalue->utranMobilityInformation_r3_add_ext.numbits, pvalue->utranMobilityInformation_r3_add_ext.data);
   }

   if (pvalue->m.v690NonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions_v690NonCriticalExtensions (
         "v690NonCriticalExtensions", &pvalue->v690NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_v3a0ext_IEs (
      "utranMobilityInformation_v3a0ext", &pvalue->
      utranMobilityInformation_v3a0ext);

   if (pvalue->m.laterNonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions_laterNonCriticalExtensions (
         "laterNonCriticalExtensions", &pvalue->laterNonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r3 
   (const char* name, const utran_UTRANMobilityInformation_r3* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r3_IEs (
      "utranMobilityInformation_r3", &pvalue->utranMobilityInformation_r3);

   if (pvalue->m.v3a0NonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_r3_v3a0NonCriticalExtensions (
         "v3a0NonCriticalExtensions", &pvalue->v3a0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r5_IEs 
   (const char* name, const utran_UTRANMobilityInformation_r5_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.integrityProtectionModeInfoPresent) {
      asn1Print_utran_IntegrityProtectionModeInfo (
         "integrityProtectionModeInfo", &pvalue->integrityProtectionModeInfo);
   }

   if (pvalue->m.cipheringModeInfoPresent) {
      asn1Print_utran_CipheringModeInfo ("cipheringModeInfo", &pvalue->
         cipheringModeInfo);
   }

   if (pvalue->m.new_U_RNTIPresent) {
      asn1Print_utran_U_RNTI ("new_U_RNTI", &pvalue->new_U_RNTI);
   }

   if (pvalue->m.new_C_RNTIPresent) {
      asn1Print_utran_C_RNTI ("new_C_RNTI", &pvalue->new_C_RNTI);
   }

   if (pvalue->m.ue_ConnTimersAndConstantsPresent) {
      asn1Print_utran_UE_ConnTimersAndConstants_r5 (
         "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);
   }

   if (pvalue->m.cn_InformationInfoPresent) {
      asn1Print_utran_CN_InformationInfoFull ("cn_InformationInfo", &pvalue->
         cn_InformationInfo);
   }

   if (pvalue->m.ura_IdentityPresent) {
      asn1Print_utran_URA_Identity ("ura_Identity", &pvalue->ura_Identity);
   }

   if (pvalue->m.dl_CounterSynchronisationInfoPresent) {
      asn1Print_utran_DL_CounterSynchronisationInfo_r5 (
         "dl_CounterSynchronisationInfo", &pvalue->
         dl_CounterSynchronisationInfo);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_v860ext1_IEs (
      "utranMobilityInformation_v860ext", &pvalue->
      utranMobilityInformation_v860ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UtranMobilityInformation_v690ext_IEs (
      "utranMobilityInformation_v690ext", &pvalue->
      utranMobilityInformation_v690ext);

   if (pvalue->m.v860NonCriticalExtentionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions_v860NonCriticalExtentions (
         "v860NonCriticalExtentions", &pvalue->v860NonCriticalExtentions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r5_IEs (
      "utranMobilityInformation_r5", &pvalue->utranMobilityInformation_r5);

   if (pvalue->m.v690NonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5_v690NonCriticalExtensions (
         "v690NonCriticalExtensions", &pvalue->v690NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r7_IEs 
   (const char* name, const utran_UTRANMobilityInformation_r7_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.integrityProtectionModeInfoPresent) {
      asn1Print_utran_IntegrityProtectionModeInfo_r7 (
         "integrityProtectionModeInfo", &pvalue->integrityProtectionModeInfo);
   }

   if (pvalue->m.cipheringModeInfoPresent) {
      asn1Print_utran_CipheringModeInfo_r7 ("cipheringModeInfo", &pvalue->
         cipheringModeInfo);
   }

   if (pvalue->m.new_U_RNTIPresent) {
      asn1Print_utran_U_RNTI ("new_U_RNTI", &pvalue->new_U_RNTI);
   }

   if (pvalue->m.new_C_RNTIPresent) {
      asn1Print_utran_C_RNTI ("new_C_RNTI", &pvalue->new_C_RNTI);
   }

   if (pvalue->m.new_H_RNTIPresent) {
      asn1Print_utran_H_RNTI ("new_H_RNTI", &pvalue->new_H_RNTI);
   }

   if (pvalue->m.ue_ConnTimersAndConstantsPresent) {
      asn1Print_utran_UE_ConnTimersAndConstants_r5 (
         "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);
   }

   if (pvalue->m.cn_InformationInfoPresent) {
      asn1Print_utran_CN_InformationInfoFull ("cn_InformationInfo", &pvalue->
         cn_InformationInfo);
   }

   if (pvalue->m.primary_plmn_IdentityPresent) {
      asn1Print_utran_PLMN_Identity ("primary_plmn_Identity", &pvalue->
         primary_plmn_Identity);
   }

   if (pvalue->m.ura_IdentityPresent) {
      asn1Print_utran_URA_Identity ("ura_Identity", &pvalue->ura_Identity);
   }

   if (pvalue->m.supportForChangeOfUE_CapabilityPresent) {
      rtxPrintIndent ();
      rtxPrintBoolean ("supportForChangeOfUE_Capability", pvalue->supportForChangeOfUE_Capability);
   }

   if (pvalue->m.dl_CounterSynchronisationInfoPresent) {
      asn1Print_utran_DL_CounterSynchronisationInfo_r5 (
         "dl_CounterSynchronisationInfo", &pvalue->
         dl_CounterSynchronisationInfo);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_v860ext2_IEs 
   (const char* name, const utran_UTRANMobilityInformation_v860ext2_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.newPrimary_E_RNTIPresent) {
      asn1Print_utran_E_RNTI ("newPrimary_E_RNTI", &pvalue->newPrimary_E_RNTI
         );
   }

   asn1Print_utran_UE_ConnTimersAndConstants_v860ext (
      "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);

   if (pvalue->m.dedicatedPriorityInformationPresent) {
      asn1Print_utran_DedicatedPriorityInformation (
         "dedicatedPriorityInformation", &pvalue->dedicatedPriorityInformation
         );
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_vb50ext_IEs 
   (const char* name, const utran_UTRANMobilityInformation_vb50ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.dedicatedPriorityInformationPresent) {
      asn1Print_utran_DedicatedPriorityInformation_r11 (
         "dedicatedPriorityInformation", &pvalue->dedicatedPriorityInformation
         );
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_vb50ext_IEs (
      "utranMobilityInformation_vb50ext", &pvalue->
      utranMobilityInformation_vb50ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_v860ext2_IEs (
      "utranMobilityInformation_v860ext", &pvalue->
      utranMobilityInformation_v860ext);

   if (pvalue->m.vb50NonCriticalExtentionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions_vb50NonCriticalExtentions (
         "vb50NonCriticalExtentions", &pvalue->vb50NonCriticalExtentions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r7_IEs (
      "utranMobilityInformation_r7", &pvalue->utranMobilityInformation_r7);

   if (pvalue->m.utranMobilityInformation_r7_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformation_r7_add_ext", pvalue->utranMobilityInformation_r7_add_ext.numbits, pvalue->utranMobilityInformation_r7_add_ext.data);
   }

   if (pvalue->m.v860NonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7_v860NonCriticalExtensions (
         "v860NonCriticalExtensions", &pvalue->v860NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r11_IEs 
   (const char* name, const utran_UTRANMobilityInformation_r11_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.integrityProtectionModeInfoPresent) {
      asn1Print_utran_IntegrityProtectionModeInfo_r7 (
         "integrityProtectionModeInfo", &pvalue->integrityProtectionModeInfo);
   }

   if (pvalue->m.cipheringModeInfoPresent) {
      asn1Print_utran_CipheringModeInfo_r7 ("cipheringModeInfo", &pvalue->
         cipheringModeInfo);
   }

   if (pvalue->m.new_U_RNTIPresent) {
      asn1Print_utran_U_RNTI ("new_U_RNTI", &pvalue->new_U_RNTI);
   }

   if (pvalue->m.new_C_RNTIPresent) {
      asn1Print_utran_C_RNTI ("new_C_RNTI", &pvalue->new_C_RNTI);
   }

   if (pvalue->m.new_H_RNTIPresent) {
      asn1Print_utran_H_RNTI ("new_H_RNTI", &pvalue->new_H_RNTI);
   }

   if (pvalue->m.newPrimary_E_RNTIPresent) {
      asn1Print_utran_E_RNTI ("newPrimary_E_RNTI", &pvalue->newPrimary_E_RNTI
         );
   }

   if (pvalue->m.ue_ConnTimersAndConstantsPresent) {
      asn1Print_utran_UE_ConnTimersAndConstants_r11 (
         "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);
   }

   if (pvalue->m.cn_InformationInfoPresent) {
      asn1Print_utran_CN_InformationInfoFull ("cn_InformationInfo", &pvalue->
         cn_InformationInfo);
   }

   if (pvalue->m.primary_plmn_IdentityPresent) {
      asn1Print_utran_PLMN_Identity ("primary_plmn_Identity", &pvalue->
         primary_plmn_Identity);
   }

   if (pvalue->m.ura_IdentityPresent) {
      asn1Print_utran_URA_Identity ("ura_Identity", &pvalue->ura_Identity);
   }

   if (pvalue->m.supportForChangeOfUE_CapabilityPresent) {
      rtxPrintIndent ();
      rtxPrintBoolean ("supportForChangeOfUE_Capability", pvalue->supportForChangeOfUE_Capability);
   }

   if (pvalue->m.dedicatedPriorityInformationPresent) {
      asn1Print_utran_DedicatedPriorityInformation_r11 (
         "dedicatedPriorityInformation", &pvalue->dedicatedPriorityInformation
         );
   }

   if (pvalue->m.dl_CounterSynchronisationInfoPresent) {
      asn1Print_utran_DL_CounterSynchronisationInfo_r5 (
         "dl_CounterSynchronisationInfo", &pvalue->
         dl_CounterSynchronisationInfo);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r11_IEs (
      "utranMobilityInformation_r11", &pvalue->utranMobilityInformation_r11);

   if (pvalue->m.utranMobilityInformation_r11_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformation_r11_add_ext", pvalue->utranMobilityInformation_r11_add_ext.numbits, pvalue->utranMobilityInformation_r11_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r12_IEs 
   (const char* name, const utran_UTRANMobilityInformation_r12_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.integrityProtectionModeInfoPresent) {
      asn1Print_utran_IntegrityProtectionModeInfo_r7 (
         "integrityProtectionModeInfo", &pvalue->integrityProtectionModeInfo);
   }

   if (pvalue->m.cipheringModeInfoPresent) {
      asn1Print_utran_CipheringModeInfo_r7 ("cipheringModeInfo", &pvalue->
         cipheringModeInfo);
   }

   if (pvalue->m.new_U_RNTIPresent) {
      asn1Print_utran_U_RNTI ("new_U_RNTI", &pvalue->new_U_RNTI);
   }

   if (pvalue->m.new_C_RNTIPresent) {
      asn1Print_utran_C_RNTI ("new_C_RNTI", &pvalue->new_C_RNTI);
   }

   if (pvalue->m.new_H_RNTIPresent) {
      asn1Print_utran_H_RNTI ("new_H_RNTI", &pvalue->new_H_RNTI);
   }

   if (pvalue->m.newPrimary_E_RNTIPresent) {
      asn1Print_utran_E_RNTI ("newPrimary_E_RNTI", &pvalue->newPrimary_E_RNTI
         );
   }

   if (pvalue->m.ue_ConnTimersAndConstantsPresent) {
      asn1Print_utran_UE_ConnTimersAndConstants_r11 (
         "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);
   }

   if (pvalue->m.measurementReleaseEnhancementPresent) {
      asn1Print_utran_MeasurementReleaseEnhancement (
         "measurementReleaseEnhancement", &pvalue->
         measurementReleaseEnhancement);
   }

   if (pvalue->m.cn_InformationInfoPresent) {
      asn1Print_utran_CN_InformationInfoFull ("cn_InformationInfo", &pvalue->
         cn_InformationInfo);
   }

   if (pvalue->m.primary_plmn_IdentityPresent) {
      asn1Print_utran_PLMN_Identity ("primary_plmn_Identity", &pvalue->
         primary_plmn_Identity);
   }

   if (pvalue->m.domainSpecificAccessRestrictionParametersUpdatePresent) {
      asn1Print_utran_DomainSpecificAccessRestrictionParam_v670ext (
         "domainSpecificAccessRestrictionParametersUpdate", &pvalue->
         domainSpecificAccessRestrictionParametersUpdate);
   }

   if (pvalue->m.pagingPermissionWithAccessControlParametersUpdatePresent) {
      asn1Print_utran_PagingPermissionWithAccessControlParameters (
         "pagingPermissionWithAccessControlParametersUpdate", &pvalue->
         pagingPermissionWithAccessControlParametersUpdate);
   }

   if (pvalue->m.ura_IdentityPresent) {
      asn1Print_utran_URA_Identity ("ura_Identity", &pvalue->ura_Identity);
   }

   if (pvalue->m.supportForChangeOfUE_CapabilityPresent) {
      rtxPrintIndent ();
      rtxPrintBoolean ("supportForChangeOfUE_Capability", pvalue->supportForChangeOfUE_Capability);
   }

   if (pvalue->m.dedicatedPriorityInformationPresent) {
      asn1Print_utran_DedicatedPriorityInformation_r11 (
         "dedicatedPriorityInformation", &pvalue->dedicatedPriorityInformation
         );
   }

   if (pvalue->m.dl_CounterSynchronisationInfoPresent) {
      asn1Print_utran_DL_CounterSynchronisationInfo_r5 (
         "dl_CounterSynchronisationInfo", &pvalue->
         dl_CounterSynchronisationInfo);
   }

   if (pvalue->m.dedicatedWLANOffloadInformationPresent) {
      asn1Print_utran_DedicatedWLANOffloadInformation (
         "dedicatedWLANOffloadInformation", &pvalue->
         dedicatedWLANOffloadInformation);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r12_IEs (
      "utranMobilityInformation_r12", &pvalue->utranMobilityInformation_r12);

   if (pvalue->m.utranMobilityInformation_r12_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformation_r12_add_ext", pvalue->utranMobilityInformation_r12_add_ext.numbits, pvalue->utranMobilityInformation_r12_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_r13_IEs 
   (const char* name, const utran_UTRANMobilityInformation_r13_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.integrityProtectionModeInfoPresent) {
      asn1Print_utran_IntegrityProtectionModeInfo_r7 (
         "integrityProtectionModeInfo", &pvalue->integrityProtectionModeInfo);
   }

   if (pvalue->m.cipheringModeInfoPresent) {
      asn1Print_utran_CipheringModeInfo_r7 ("cipheringModeInfo", &pvalue->
         cipheringModeInfo);
   }

   if (pvalue->m.new_U_RNTIPresent) {
      asn1Print_utran_U_RNTI ("new_U_RNTI", &pvalue->new_U_RNTI);
   }

   if (pvalue->m.new_C_RNTIPresent) {
      asn1Print_utran_C_RNTI ("new_C_RNTI", &pvalue->new_C_RNTI);
   }

   if (pvalue->m.new_H_RNTIPresent) {
      asn1Print_utran_H_RNTI ("new_H_RNTI", &pvalue->new_H_RNTI);
   }

   if (pvalue->m.newPrimary_E_RNTIPresent) {
      asn1Print_utran_E_RNTI ("newPrimary_E_RNTI", &pvalue->newPrimary_E_RNTI
         );
   }

   if (pvalue->m.ue_ConnTimersAndConstantsPresent) {
      asn1Print_utran_UE_ConnTimersAndConstants_r11 (
         "ue_ConnTimersAndConstants", &pvalue->ue_ConnTimersAndConstants);
   }

   if (pvalue->m.measurementReleaseEnhancementPresent) {
      asn1Print_utran_MeasurementReleaseEnhancement (
         "measurementReleaseEnhancement", &pvalue->
         measurementReleaseEnhancement);
   }

   if (pvalue->m.cn_InformationInfoPresent) {
      asn1Print_utran_CN_InformationInfoFull ("cn_InformationInfo", &pvalue->
         cn_InformationInfo);
   }

   if (pvalue->m.primary_plmn_IdentityPresent) {
      asn1Print_utran_PLMN_Identity ("primary_plmn_Identity", &pvalue->
         primary_plmn_Identity);
   }

   if (pvalue->m.domainSpecificAccessRestrictionParametersUpdatePresent) {
      asn1Print_utran_DomainSpecificAccessRestrictionParam_v670ext (
         "domainSpecificAccessRestrictionParametersUpdate", &pvalue->
         domainSpecificAccessRestrictionParametersUpdate);
   }

   if (pvalue->m.pagingPermissionWithAccessControlParametersUpdatePresent) {
      asn1Print_utran_PagingPermissionWithAccessControlParameters (
         "pagingPermissionWithAccessControlParametersUpdate", &pvalue->
         pagingPermissionWithAccessControlParametersUpdate);
   }

   if (pvalue->m.ura_IdentityPresent) {
      asn1Print_utran_URA_Identity ("ura_Identity", &pvalue->ura_Identity);
   }

   if (pvalue->m.supportForChangeOfUE_CapabilityPresent) {
      rtxPrintIndent ();
      rtxPrintBoolean ("supportForChangeOfUE_Capability", pvalue->supportForChangeOfUE_Capability);
   }

   if (pvalue->m.extendedDedicatedPriorityInformationPresent) {
      asn1Print_utran_DedicatedPriorityInformation_r13 (
         "extendedDedicatedPriorityInformation", &pvalue->
         extendedDedicatedPriorityInformation);
   }

   if (pvalue->m.dl_CounterSynchronisationInfoPresent) {
      asn1Print_utran_DL_CounterSynchronisationInfo_r5 (
         "dl_CounterSynchronisationInfo", &pvalue->
         dl_CounterSynchronisationInfo);
   }

   if (pvalue->m.dedicatedWLANOffloadInformationPresent) {
      asn1Print_utran_DedicatedWLANOffloadInformation (
         "dedicatedWLANOffloadInformation", &pvalue->
         dedicatedWLANOffloadInformation);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformation_r13_IEs (
      "utranMobilityInformation_r13", &pvalue->utranMobilityInformation_r13);

   if (pvalue->m.utranMobilityInformation_r13_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformation_r13_add_ext", pvalue->utranMobilityInformation_r13_add_ext.numbits, pvalue->utranMobilityInformation_r13_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r13 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r13 (
            "r13", pvalue->u.r13);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r12 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_r12 (
            "r12", pvalue->u.r12);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r11 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_r11 (
            "r11", pvalue->u.r11);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r7 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_r7 (
            "r7", pvalue->u.r7);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r5 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_r5 (
            "r5", pvalue->u.r5);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation_later_than_r3 
   (const char* name, const utran_UTRANMobilityInformation_later_than_r3* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   asn1Print_utran_UTRANMobilityInformation_later_than_r3_criticalExtensions (
      "criticalExtensions", &pvalue->criticalExtensions);

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformation 
   (const char* name, const utran_UTRANMobilityInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r3 */
      case 1:
      {
         asn1Print_utran_UTRANMobilityInformation_r3 ("r3", pvalue->u.r3);
         break;
      }
      /* later-than-r3 */
      case 2:
      {
         asn1Print_utran_UTRANMobilityInformation_later_than_r3 (
            "later-than-r3", pvalue->u.later_than_r3);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm_v770ext_IEs 
   (const char* name, const utran_UTRANMobilityInformationConfirm_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.deferredMeasurementControlReadingPresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_v770ext_IEs_deferredMeasurementControlReading (
         "deferredMeasurementControlReading", &pvalue->
         deferredMeasurementControlReading);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm_va40ext_IEs 
   (const char* name, const utran_UTRANMobilityInformationConfirm_va40ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasAvailablePresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_va40ext_IEs_loggedMeasAvailable (
         "loggedMeasAvailable", &pvalue->loggedMeasAvailable);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformationConfirm_va40ext_IEs (
      "utranMobilityInformationConfirm_va40ext", &pvalue->
      utranMobilityInformationConfirm_va40ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension 
   (const char* name, const utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UTRANMobilityInformationConfirm_v770ext_IEs (
      "utranMobilityInformationConfirm_v770ext", &pvalue->
      utranMobilityInformationConfirm_v770ext);

   if (pvalue->m.va40NonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension_va40NonCriticalExtensions (
         "va40NonCriticalExtensions", &pvalue->va40NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.utranMobilityInformationConfirm_r3_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformationConfirm_r3_add_ext", pvalue->utranMobilityInformationConfirm_r3_add_ext.numbits, pvalue->utranMobilityInformationConfirm_r3_add_ext.data);
   }

   if (pvalue->m.v770NonCriticalExtensionPresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions_v770NonCriticalExtension (
         "v770NonCriticalExtension", &pvalue->v770NonCriticalExtension);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationConfirm 
   (const char* name, const utran_UTRANMobilityInformationConfirm* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   if (pvalue->m.ul_IntegProtActivationInfoPresent) {
      asn1Print_utran_IntegrityProtActivationInfo (
         "ul_IntegProtActivationInfo", &pvalue->ul_IntegProtActivationInfo);
   }

   if (pvalue->m.count_C_ActivationTimePresent) {
      asn1Print_utran_ActivationTime ("count_C_ActivationTime", &pvalue->
         count_C_ActivationTime);
   }

   if (pvalue->m.dummyPresent) {
      asn1Print_utran_RB_ActivationTimeInfoList ("dummy", &pvalue->dummy);
   }

   if (pvalue->m.ul_CounterSynchronisationInfoPresent) {
      asn1Print_utran_UL_CounterSynchronisationInfo (
         "ul_CounterSynchronisationInfo", &pvalue->
         ul_CounterSynchronisationInfo);
   }

   if (pvalue->m.laterNonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformationConfirm_laterNonCriticalExtensions (
         "laterNonCriticalExtensions", &pvalue->laterNonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions 
   (const char* name, const utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.utranMobilityInformationFailure_r3_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("utranMobilityInformationFailure_r3_add_ext", pvalue->utranMobilityInformationFailure_r3_add_ext.numbits, pvalue->utranMobilityInformationFailure_r3_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UTRANMobilityInformationFailure 
   (const char* name, const utran_UTRANMobilityInformationFailure* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   asn1Print_utran_FailureCauseWithProtErr ("failureCause", &pvalue->
      failureCause);

   if (pvalue->m.laterNonCriticalExtensionsPresent) {
      asn1Print_utran_UTRANMobilityInformationFailure_laterNonCriticalExtensions (
         "laterNonCriticalExtensions", &pvalue->laterNonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSAccessInformation_nonCriticalExtensions 
   (const char* name, const utran_MBMSAccessInformation_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSAccessInformation 
   (const char* name, const utran_MBMSAccessInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMS_ServiceAccessInfoList_r6 (
      "mbms_ServiceAccessInfoList", &pvalue->mbms_ServiceAccessInfoList);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSAccessInformation_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v770ext_IEs 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbms_PhyChInformationList_r7Present) {
      asn1Print_utran_MBMS_PhyChInformationList_r7 (
         "mbms_PhyChInformationList_r7", &pvalue->mbms_PhyChInformationList_r7
         );
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v780ext_IEs 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v780ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbsfn_TDDInformation_LCRPresent) {
      asn1Print_utran_MBSFN_TDDInformation_LCR ("mbsfn_TDDInformation_LCR", &
         pvalue->mbsfn_TDDInformation_LCR);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v860ext_IEs 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v860ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbms_PhyChInformationListPresent) {
      asn1Print_utran_MBMS_PhyChInformationList_IMB384 (
         "mbms_PhyChInformationList", &pvalue->mbms_PhyChInformationList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSCommonPTMRBInformation_v860ext_IEs (
      "mbmsCommonPTMRBInformation_v860ext", &pvalue->
      mbmsCommonPTMRBInformation_v860ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSCommonPTMRBInformation_v780ext_IEs (
      "mbmsCommonPTMRBInformation_v780ext", &pvalue->
      mbmsCommonPTMRBInformation_v780ext);

   if (pvalue->m.v860NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions_v860NonCriticalExtensions (
         "v860NonCriticalExtensions", &pvalue->v860NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSCommonPTMRBInformation_v770ext_IEs (
      "mbmsCommonPTMRBInformation_v770ext", &pvalue->
      mbmsCommonPTMRBInformation_v770ext);

   if (pvalue->m.v780NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions_v780NonCriticalExtensions (
         "v780NonCriticalExtensions", &pvalue->v780NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCommonPTMRBInformation 
   (const char* name, const utran_MBMSCommonPTMRBInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMS_CommonRBInformationList_r6 (
      "mbms_CommonRBInformationList", &pvalue->mbms_CommonRBInformationList);

   asn1Print_utran_MBMS_TranspChInfoForEachTrCh_r6 (
      "mbms_TranspChInfoForEachTrCh", &pvalue->mbms_TranspChInfoForEachTrCh);

   if (pvalue->m.mbms_TranspChInfoForEachCCTrChPresent) {
      asn1Print_utran_MBMS_TranspChInfoForEachCCTrCh_r6 (
         "mbms_TranspChInfoForEachCCTrCh", &pvalue->
         mbms_TranspChInfoForEachCCTrCh);
   }

   asn1Print_utran_MBMS_PhyChInformationList_r6 ("mbms_PhyChInformationList", &
      pvalue->mbms_PhyChInformationList);

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCommonPTMRBInformation_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCurrentCellPTMRBInfo_v770ext_IEs 
   (const char* name, const utran_MBMSCurrentCellPTMRBInfo_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbsfn_TDM_Info_ListPresent) {
      asn1Print_utran_MBSFN_TDM_Info_List ("mbsfn_TDM_Info_List", &pvalue->
         mbsfn_TDM_Info_List);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSCurrentCellPTMRBInfo_v770ext_IEs (
      "mbmsCurrentCellPTMRBInfo_v770ext", &pvalue->
      mbmsCurrentCellPTMRBInfo_v770ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSCurrentCellPTMRBInformation 
   (const char* name, const utran_MBMSCurrentCellPTMRBInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbms_CurrentCell_SCCPCHListPresent) {
      asn1Print_utran_MBMS_CurrentCell_SCCPCHList_r6 (
         "mbms_CurrentCell_SCCPCHList", &pvalue->mbms_CurrentCell_SCCPCHList);
   }

   if (pvalue->m.mbms_SIBType5_SCCPCHListPresent) {
      asn1Print_utran_MBMS_SIBType5_SCCPCHList_r6 ("mbms_SIBType5_SCCPCHList", 
         &pvalue->mbms_SIBType5_SCCPCHList);
   }

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSCurrentCellPTMRBInformation_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v6b0ext_IEs 
   (const char* name, const utran_MBMSGeneralInformation_v6b0ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintIndent ();
   rtxPrintBoolean ("indicateChangeInSelectedServices", pvalue->indicateChangeInSelectedServices);

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v770ext_IEs 
   (const char* name, const utran_MBMSGeneralInformation_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbmsMICHConfigurationPresent) {
      asn1Print_utran_MBMS_MICHConfigurationInfo_v770ext (
         "mbmsMICHConfiguration", &pvalue->mbmsMICHConfiguration);
   }

   if (pvalue->m.mbsfnInterFrequencyNeighbourListPresent) {
      asn1Print_utran_MBSFN_InterFrequencyNeighbourList_r7 (
         "mbsfnInterFrequencyNeighbourList", &pvalue->
         mbsfnInterFrequencyNeighbourList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v860ext_IEs 
   (const char* name, const utran_MBMSGeneralInformation_v860ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbsfnInterFrequencyNeighbourListPresent) {
      asn1Print_utran_MBSFN_InterFrequencyNeighbourList_v860ext (
         "mbsfnInterFrequencyNeighbourList", &pvalue->
         mbsfnInterFrequencyNeighbourList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v890ext_IEs 
   (const char* name, const utran_MBMSGeneralInformation_v890ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbmsNetworkStandardTimeInformation_LCRPresent) {
      asn1Print_utran_MBMS_NetworkStandardTimeInformation_LCR_v890ext (
         "mbmsNetworkStandardTimeInformation_LCR", &pvalue->
         mbmsNetworkStandardTimeInformation_LCR);
   }

   if (pvalue->m.mbmsMICHConfigurationPresent) {
      asn1Print_utran_MBMS_MICHConfigurationInfo_v890ext (
         "mbmsMICHConfiguration", &pvalue->mbmsMICHConfiguration);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions 
   (const char* name, const utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSGeneralInformation_v890ext_IEs (
      "mbmsGeneralInformation_v890ext", &pvalue->mbmsGeneralInformation_v890ext
      );

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions 
   (const char* name, const utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSGeneralInformation_v860ext_IEs (
      "mbmsGeneralInformation_v860ext", &pvalue->mbmsGeneralInformation_v860ext
      );

   if (pvalue->m.v890NoncriticalExtensionsPresent) {
      asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions_v890NoncriticalExtensions (
         "v890NoncriticalExtensions", &pvalue->v890NoncriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSGeneralInformation_v770ext_IEs (
      "mbmsGeneralInformation_v770ext", &pvalue->mbmsGeneralInformation_v770ext
      );

   if (pvalue->m.v860NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions_v860NonCriticalExtensions (
         "v860NonCriticalExtensions", &pvalue->v860NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions 
   (const char* name, const utran_MBMSGeneralInformation_v6b0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSGeneralInformation_v6b0ext_IEs (
      "mbmsGeneralInformation_v6b0ext", &pvalue->mbmsGeneralInformation_v6b0ext
      );

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSGeneralInformation 
   (const char* name, const utran_MBMSGeneralInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbms_PreferredFrequencyInfoPresent) {
      asn1Print_utran_MBMS_PreferredFrequencyList_r6 (
         "mbms_PreferredFrequencyInfo", &pvalue->mbms_PreferredFrequencyInfo);
   }

   asn1Print_utran_MBMS_TimersAndCounters_r6 ("mbms_TimersAndCounters", &pvalue
      ->mbms_TimersAndCounters);

   asn1Print_utran_MBMS_MICHConfigurationInfo_r6 ("michConfigurationInfo", &
      pvalue->michConfigurationInfo);

   asn1Print_utran_MBMS_CellGroupIdentity_r6 ("cellGroupIdentity", &pvalue->
      cellGroupIdentity);

   if (pvalue->m.mschDefaultConfigurationInfoPresent) {
      asn1Print_utran_MBMS_MSCH_ConfigurationInfo_r6 (
         "mschDefaultConfigurationInfo", &pvalue->mschDefaultConfigurationInfo
         );
   }

   if (pvalue->m.v6b0NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSGeneralInformation_v6b0NonCriticalExtensions (
         "v6b0NonCriticalExtensions", &pvalue->v6b0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModificationRequest_v6b0ext_IEs 
   (const char* name, const utran_MBMSModificationRequest_v6b0ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMS_SelectedServiceInfo ("mbmsSelectedServiceInfo", &pvalue
      ->mbmsSelectedServiceInfo);

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModificationRequest_v6f0ext_IEs 
   (const char* name, const utran_MBMSModificationRequest_v6f0ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbmsSupportOfServiceChangeForAPtpRBPresent) {
      asn1Print_utran_MBMSModificationRequest_v6f0ext_IEs_mbmsSupportOfServiceChangeForAPtpRB (
         "mbmsSupportOfServiceChangeForAPtpRB", &pvalue->
         mbmsSupportOfServiceChangeForAPtpRB);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions 
   (const char* name, const utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSModificationRequest_v6f0ext_IEs (
      "mbmsModificationRequest_v6f0ext", &pvalue->
      mbmsModificationRequest_v6f0ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions 
   (const char* name, const utran_MBMSModificationRequest_v6b0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSModificationRequest_v6b0ext_IEs (
      "mbmsModificationRequest_v6b0ext", &pvalue->
      mbmsModificationRequest_v6b0ext);

   if (pvalue->m.v6f0NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions_v6f0NonCriticalExtensions (
         "v6f0NonCriticalExtensions", &pvalue->v6f0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModificationRequest 
   (const char* name, const utran_MBMSModificationRequest* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.mbms_PreferredFreqRequestPresent) {
      asn1Print_utran_MBMS_ServiceIdentity_r6 ("mbms_PreferredFreqRequest", &
         pvalue->mbms_PreferredFreqRequest);
   }

   if (pvalue->m.rb_InformationReleaseListPresent) {
      asn1Print_utran_RB_InformationReleaseList ("rb_InformationReleaseList", &
         pvalue->rb_InformationReleaseList);
   }

   if (pvalue->m.v6b0NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModificationRequest_v6b0NonCriticalExtensions (
         "v6b0NonCriticalExtensions", &pvalue->v6b0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModifiedServicesInformation_v770ext_IEs 
   (const char* name, const utran_MBMSModifiedServicesInformation_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.modifiedServiceListPresent) {
      asn1Print_utran_MBMS_ModifiedServiceList_v770ext ("modifiedServiceList", 
         &pvalue->modifiedServiceList);
   }

   if (pvalue->m.mib_ValueTagPresent) {
      asn1Print_utran_MIB_ValueTag ("mib_ValueTag", &pvalue->mib_ValueTag);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModifiedServicesInformation_v7c0ext_IEs 
   (const char* name, const utran_MBMSModifiedServicesInformation_v7c0ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.modifiedServiceListPresent) {
      asn1Print_utran_MBMS_ModifiedServiceList_LCR_v7c0ext (
         "modifiedServiceList", &pvalue->modifiedServiceList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions 
   (const char* name, const utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSModifiedServicesInformation_v7c0ext_IEs (
      "mbmsModifiedServicesInformation_v7c0ext", &pvalue->
      mbmsModifiedServicesInformation_v7c0ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSModifiedServicesInformation_v770ext_IEs (
      "mbmsModifiedServicesInformation_v770ext", &pvalue->
      mbmsModifiedServicesInformation_v770ext);

   if (pvalue->m.v7c0NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions_v7c0NonCriticalExtensions (
         "v7c0NonCriticalExtensions", &pvalue->v7c0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSModifiedServicesInformation 
   (const char* name, const utran_MBMSModifiedServicesInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.modifedServiceListPresent) {
      asn1Print_utran_MBMS_ModifedServiceList_r6 ("modifedServiceList", &pvalue
         ->modifedServiceList);
   }

   if (pvalue->m.mbms_ReacquireMCCHPresent) {
      asn1Print_utran_MBMSModifiedServicesInformation_mbms_ReacquireMCCH (
         "mbms_ReacquireMCCH", &pvalue->mbms_ReacquireMCCH);
   }

   if (pvalue->m.mbms_DynamicPersistenceLevelPresent) {
      asn1Print_utran_DynamicPersistenceLevel ("mbms_DynamicPersistenceLevel", 
         &pvalue->mbms_DynamicPersistenceLevel);
   }

   if (pvalue->m.endOfModifiedMCCHInformationPresent) {
      rtxPrintIndent ();
      rtxPrintUnsigned ("endOfModifiedMCCHInformation", pvalue->endOfModifiedMCCHInformation);
   }

   asn1Print_utran_MBMS_NumberOfNeighbourCells_r6 (
      "mbmsNumberOfNeighbourCells", &pvalue->mbmsNumberOfNeighbourCells);

   if (pvalue->m.mbms_AllUnmodifiedPTMServicesPresent) {
      asn1Print_utran_MBMSModifiedServicesInformation_mbms_AllUnmodifiedPTMServices (
         "mbms_AllUnmodifiedPTMServices", &pvalue->
         mbms_AllUnmodifiedPTMServices);
   }

   if (pvalue->m.mbms_PTMActivationTimePresent) {
      asn1Print_utran_MBMS_PTMActivationTime_r6 ("mbms_PTMActivationTime", &
         pvalue->mbms_PTMActivationTime);
   }

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSModifiedServicesInformation_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770ext_IEs 
   (const char* name, const utran_MBMSNeighbouringCellPTMRBInformation_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.neighbouringCellSCCPCHListPresent) {
      asn1Print_utran_MBMS_NeighbouringCellSCCPCHList_v770ext (
         "neighbouringCellSCCPCHList", &pvalue->neighbouringCellSCCPCHList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770ext_IEs (
      "mbmsNeighbouringCellPTMRBInformation_v770ext", &pvalue->
      mbmsNeighbouringCellPTMRBInformation_v770ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSNeighbouringCellPTMRBInformation 
   (const char* name, const utran_MBMSNeighbouringCellPTMRBInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_IntraFreqCellID ("neighbouringCellIdentity", &pvalue->
      neighbouringCellIdentity);

   asn1Print_utran_MBMS_NeighbouringCellSCCPCHList_r6 (
      "neighbouringCellSCCPCHList", &pvalue->neighbouringCellSCCPCHList);

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSNeighbouringCellPTMRBInformation_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSSchedulingInformation_nonCriticalExtensions 
   (const char* name, const utran_MBMSSchedulingInformation_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSSchedulingInformation 
   (const char* name, const utran_MBMSSchedulingInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMS_ServiceSchedulingInfoList_r6 (
      "serviceSchedulingInfoList", &pvalue->serviceSchedulingInfoList);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSSchedulingInformation_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSUnmodifiedServicesInformation_v770ext_IEs 
   (const char* name, const utran_MBMSUnmodifiedServicesInformation_v770ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.unmodifiedServiceListPresent) {
      asn1Print_utran_MBMS_UnmodifiedServiceList_v770ext (
         "unmodifiedServiceList", &pvalue->unmodifiedServiceList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions 
   (const char* name, const utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_MBMSUnmodifiedServicesInformation_v770ext_IEs (
      "mbmsUnmodifiedServicesInformation_v770ext", &pvalue->
      mbmsUnmodifiedServicesInformation_v770ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_MBMSUnmodifiedServicesInformation 
   (const char* name, const utran_MBMSUnmodifiedServicesInformation* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.unmodifiedServiceListPresent) {
      asn1Print_utran_MBMS_UnmodifiedServiceList_r6 ("unmodifiedServiceList", &
         pvalue->unmodifiedServiceList);
   }

   if (pvalue->m.v770NonCriticalExtensionsPresent) {
      asn1Print_utran_MBMSUnmodifiedServicesInformation_v770NonCriticalExtensions (
         "v770NonCriticalExtensions", &pvalue->v770NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_System_Information_Container_vb50ext_IEs 
   (const char* name, const utran_System_Information_Container_vb50ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.sysInfoType22Present) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoType22", pvalue->sysInfoType22.numocts, pvalue->sysInfoType22.data);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_System_Information_Container_vc50ext_IEs 
   (const char* name, const utran_System_Information_Container_vc50ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.sysInfoType11terPresent) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoType11ter", pvalue->sysInfoType11ter.numocts, pvalue->sysInfoType11ter.data);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions 
   (const char* name, const utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_System_Information_Container_vc50ext_IEs (
      "system_Information_Container_vc50ext", &pvalue->
      system_Information_Container_vc50ext);

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions 
   (const char* name, const utran_System_Information_Container_vb50NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_System_Information_Container_vb50ext_IEs (
      "system_Information_Container_vb50ext", &pvalue->
      system_Information_Container_vb50ext);

   if (pvalue->m.vc50NonCriticalExtensionsPresent) {
      asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions_vc50NonCriticalExtensions (
         "vc50NonCriticalExtensions", &pvalue->vc50NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_System_Information_Container 
   (const char* name, const utran_System_Information_Container* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintIndent ();
   rtxPrintHexStr ("mib", pvalue->mib.numocts, pvalue->mib.data);

   if (pvalue->m.sysInfoTypeSB1Present) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoTypeSB1", pvalue->sysInfoTypeSB1.numocts, pvalue->sysInfoTypeSB1.data);
   }

   if (pvalue->m.sysInfoTypeSB2Present) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoTypeSB2", pvalue->sysInfoTypeSB2.numocts, pvalue->sysInfoTypeSB2.data);
   }

   rtxPrintIndent ();
   rtxPrintHexStr ("sysInfoType1", pvalue->sysInfoType1.numocts, pvalue->sysInfoType1.data);

   rtxPrintIndent ();
   rtxPrintHexStr ("sysInfoType3", pvalue->sysInfoType3.numocts, pvalue->sysInfoType3.data);

   rtxPrintIndent ();
   rtxPrintHexStr ("sysInfoType5", pvalue->sysInfoType5.numocts, pvalue->sysInfoType5.data);

   rtxPrintIndent ();
   rtxPrintHexStr ("sysInfoType7", pvalue->sysInfoType7.numocts, pvalue->sysInfoType7.data);

   if (pvalue->m.sysInfoType11Present) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoType11", pvalue->sysInfoType11.numocts, pvalue->sysInfoType11.data);
   }

   if (pvalue->m.sysInfoType11bisPresent) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoType11bis", pvalue->sysInfoType11bis.numocts, pvalue->sysInfoType11bis.data);
   }

   if (pvalue->m.sysInfoType12Present) {
      rtxPrintIndent ();
      rtxPrintHexStr ("sysInfoType12", pvalue->sysInfoType12.numocts, pvalue->sysInfoType12.data);
   }

   if (pvalue->m.vb50NonCriticalExtensionsPresent) {
      asn1Print_utran_System_Information_Container_vb50NonCriticalExtensions (
         "vb50NonCriticalExtensions", &pvalue->vb50NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_r10_IEs 
   (const char* name, const utran_LoggingMeasurementConfiguration_r10_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasurementsConfigurationInfoPresent) {
      asn1Print_utran_LoggedMeasurementsConfigurationInfo (
         "loggedMeasurementsConfigurationInfo", &pvalue->
         loggedMeasurementsConfigurationInfo);
   }

   if (pvalue->m.loggedANRConfigurationInfoPresent) {
      asn1Print_utran_LoggedANRConfigurationInfo (
         "loggedANRConfigurationInfo", &pvalue->loggedANRConfigurationInfo);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_r10_nonCriticalExtensions 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_r10_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_r10 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_r10* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_LoggingMeasurementConfiguration_r10_IEs (
      "loggingMeasurementConfiguration_r10_IEs", &pvalue->
      loggingMeasurementConfiguration_r10_IEs);

   if (pvalue->m.loggingMeasurementConfiguration_r10_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("loggingMeasurementConfiguration_r10_add_ext", pvalue->loggingMeasurementConfiguration_r10_add_ext.numbits, pvalue->loggingMeasurementConfiguration_r10_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_r10_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_r11_IEs 
   (const char* name, const utran_LoggingMeasurementConfiguration_r11_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasurementsConfigurationInfoPresent) {
      asn1Print_utran_LoggedMeasurementsConfigurationInfo_r11 (
         "loggedMeasurementsConfigurationInfo", &pvalue->
         loggedMeasurementsConfigurationInfo);
   }

   if (pvalue->m.loggedANRConfigurationInfoPresent) {
      asn1Print_utran_LoggedANRConfigurationInfo (
         "loggedANRConfigurationInfo", &pvalue->loggedANRConfigurationInfo);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_LoggingMeasurementConfiguration_r11_IEs (
      "loggingMeasurementConfiguration_r11_IEs", &pvalue->
      loggingMeasurementConfiguration_r11_IEs);

   if (pvalue->m.loggingMeasurementConfiguration_r11_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("loggingMeasurementConfiguration_r11_add_ext", pvalue->loggingMeasurementConfiguration_r11_add_ext.numbits, pvalue->loggingMeasurementConfiguration_r11_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r11 */
      case 1:
      {
         asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_r11 (
            "r11", pvalue->u.r11);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions 
   (const char* name, const utran_LoggingMeasurementConfiguration_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r10 */
      case 1:
      {
         asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_r10 (
            "r10", pvalue->u.r10);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_LoggingMeasurementConfiguration 
   (const char* name, const utran_LoggingMeasurementConfiguration* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   asn1Print_utran_LoggingMeasurementConfiguration_criticalExtensions (
      "criticalExtensions", &pvalue->criticalExtensions);

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vb50ext_IEs 
   (const char* name, const utran_UEInformationResponse_vb50ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasReportPresent) {
      asn1Print_utran_LoggedMeasReport_vb50ext ("loggedMeasReport", &pvalue->
         loggedMeasReport);
   }

   if (pvalue->m.dummyPresent) {
      asn1Print_utran_ConnectionEstablishmentFailureReport ("dummy", &pvalue->
         dummy);
   }

   if (pvalue->m.loggedANRReportInfoListPresent) {
      asn1Print_utran_LoggedANRReportInfoList_vb50ext (
         "loggedANRReportInfoList", &pvalue->loggedANRReportInfoList);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vbb0ext_IEs 
   (const char* name, const utran_UEInformationResponse_vbb0ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.connectionEstablishmentFailureReportPresent) {
      asn1Print_utran_ConnectionEstablishmentFailureReport_r11 (
         "connectionEstablishmentFailureReport", &pvalue->
         connectionEstablishmentFailureReport);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vc50ext_IEs 
   (const char* name, const utran_UEInformationResponse_vc50ext_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasReportPresent) {
      asn1Print_utran_LoggedMeasReport_vc50ext ("loggedMeasReport", &pvalue->
         loggedMeasReport);
   }

   if (pvalue->m.connectionEstablishmentFailureReportPresent) {
      asn1Print_utran_ConnectionEstablishmentFailureReport_vc50ext (
         "connectionEstablishmentFailureReport", &pvalue->
         connectionEstablishmentFailureReport);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions 
   (const char* name, const utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions 
   (const char* name, const utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UEInformationResponse_vc50ext_IEs (
      "ueInformationResponse_vc50ext", &pvalue->ueInformationResponse_vc50ext
      );

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions 
   (const char* name, const utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UEInformationResponse_vbb0ext_IEs (
      "ueInformationResponse_vbb0ext", &pvalue->ueInformationResponse_vbb0ext
      );

   if (pvalue->m.vc50NonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions_vc50NonCriticalExtensions (
         "vc50NonCriticalExtensions", &pvalue->vc50NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions 
   (const char* name, const utran_UEInformationResponse_vb50NonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UEInformationResponse_vb50ext_IEs (
      "ueInformationResponse_vb50ext", &pvalue->ueInformationResponse_vb50ext
      );

   if (pvalue->m.vbb0NonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions_vbb0NonCriticalExtensions (
         "vbb0NonCriticalExtensions", &pvalue->vbb0NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationResponse 
   (const char* name, const utran_UEInformationResponse* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   if (pvalue->m.loggedMeasReportPresent) {
      asn1Print_utran_LoggedMeasReport ("loggedMeasReport", &pvalue->
         loggedMeasReport);
   }

   if (pvalue->m.loggedANRReportInfoListPresent) {
      asn1Print_utran_LoggedANRReportInfoList ("loggedANRReportInfoList", &
         pvalue->loggedANRReportInfoList);
   }

   if (pvalue->m.vb50NonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationResponse_vb50NonCriticalExtensions (
         "vb50NonCriticalExtensions", &pvalue->vb50NonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_r10_IEs 
   (const char* name, const utran_UEInformationRequest_r10_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasReportRequestPresent) {
      asn1Print_utran_UEInformationRequest_r10_IEs_loggedMeasReportRequest (
         "loggedMeasReportRequest", &pvalue->loggedMeasReportRequest);
   }

   if (pvalue->m.loggedANRReportRequestPresent) {
      asn1Print_utran_UEInformationRequest_r10_IEs_loggedANRReportRequest (
         "loggedANRReportRequest", &pvalue->loggedANRReportRequest);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_criticalExtensions_r10_nonCriticalExtensions 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_r10_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UEInformationRequest_criticalExtensions_r10 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_r10* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UEInformationRequest_r10_IEs ("ueInformationRequest_r10", &
      pvalue->ueInformationRequest_r10);

   if (pvalue->m.ueInformationRequest_r10_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("ueInformationRequest_r10_add_ext", pvalue->ueInformationRequest_r10_add_ext.numbits, pvalue->ueInformationRequest_r10_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationRequest_criticalExtensions_r10_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_r11_IEs 
   (const char* name, const utran_UEInformationRequest_r11_IEs* pvalue)
{
   rtxPrintOpenBrace (name);

   if (pvalue->m.loggedMeasReportRequestPresent) {
      asn1Print_utran_UEInformationRequest_r11_IEs_loggedMeasReportRequest (
         "loggedMeasReportRequest", &pvalue->loggedMeasReportRequest);
   }

   if (pvalue->m.loggedANRReportRequestPresent) {
      asn1Print_utran_UEInformationRequest_r11_IEs_loggedANRReportRequest (
         "loggedANRReportRequest", &pvalue->loggedANRReportRequest);
   }

   if (pvalue->m.connectionEstablishmentFailureRequestPresent) {
      asn1Print_utran_UEInformationRequest_r11_IEs_connectionEstablishmentFailureRequest (
         "connectionEstablishmentFailureRequest", &pvalue->
         connectionEstablishmentFailureRequest);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_UEInformationRequest_r11_IEs ("ueInformationRequest_r11", &
      pvalue->ueInformationRequest_r11);

   if (pvalue->m.ueInformationRequest_r11_add_extPresent) {
      rtxPrintIndent ();
      rtPrintBitStrBraceText ("ueInformationRequest_r11_add_ext", pvalue->ueInformationRequest_r11_add_ext.numbits, pvalue->ueInformationRequest_r11_add_ext.data);
   }

   if (pvalue->m.nonCriticalExtensionsPresent) {
      asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11_nonCriticalExtensions (
         "nonCriticalExtensions", &pvalue->nonCriticalExtensions);
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   rtxPrintCloseBrace ();
   OS_UNUSED_ARG (pvalue);

}

void asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions 
   (const char* name, const utran_UEInformationRequest_criticalExtensions_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r11 */
      case 1:
      {
         asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_r11 (
            "r11", pvalue->u.r11);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest_criticalExtensions 
   (const char* name, const utran_UEInformationRequest_criticalExtensions* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* r10 */
      case 1:
      {
         asn1Print_utran_UEInformationRequest_criticalExtensions_r10 ("r10", 
            pvalue->u.r10);
         break;
      }
      /* criticalExtensions */
      case 2:
      {
         asn1Print_utran_UEInformationRequest_criticalExtensions_criticalExtensions (
            "criticalExtensions", pvalue->u.criticalExtensions);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void asn1Print_utran_UEInformationRequest 
   (const char* name, const utran_UEInformationRequest* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_utran_RRC_TransactionIdentifier ("rrc_TransactionIdentifier", &
      pvalue->rrc_TransactionIdentifier);

   asn1Print_utran_UEInformationRequest_criticalExtensions (
      "criticalExtensions", &pvalue->criticalExtensions);

   rtxPrintCloseBrace ();
}

