/******************************************************************************
*
*   FILE NAME:
*       rrc_llim_uemh_fsm.h
*
*   DESCRIPTION:
*       This header file contains declaration for UEMH FSM
*
*   DATE            AUTHOR      REFERENCE       REASON
*   19 May 2009     VasylS      ---------       Initial
*
*   Copyright (c) 2009, Aricent Inc. All Rights Reserved
*
******************************************************************************/

#ifndef _RRC_LLIM_UEMH_FSM_H_
#define _RRC_LLIM_UEMH_FSM_H_

#include "rrc_llim_global_ctx.h"
#include "rrc_llim_timers.h"
#include "rrc_llim_ue_ctx.h"
#include "rrc_uemh_fsm_states.h"
#include "rrc_llim_logger.h"

/* CLPC Start */
#include "uecc_utils.h"

/* CLPC Stop */

/* keep in sync with uemh_fsm_tbl! */
typedef enum
{
    UEMH_EVENT_UECC_CREATE_UE_ENTITY_REQ,
    UEMH_EVENT_PHY_CREATE_UE_ENTITY_CNF,
    UEMH_EVENT_MAC_CREATE_UE_ENTITY_CNF,
    UEMH_EVENT_RLC_CREATE_UE_ENTITY_CNF,
    UEMH_EVENT_PDCP_CREATE_UE_ENTITY_CNF,
    UEMH_EVENT_S1U_CREATE_UE_ENTITY_CNF,
    UEMH_EVENT_CREATE_UE_TIMER_EXPIRED,

    UEMH_EVENT_UECC_DELETE_UE_ENTITY_REQ,
    UEMH_EVENT_PHY_DELETE_UE_ENTITY_CNF,
    UEMH_EVENT_MAC_DELETE_UE_ENTITY_CNF,
    UEMH_EVENT_RLC_DELETE_UE_ENTITY_CNF,
    UEMH_EVENT_PDCP_DELETE_UE_ENTITY_CNF,
    UEMH_EVENT_S1U_DELETE_UE_ENTITY_CNF,
    UEMH_EVENT_DELETE_UE_TIMER_EXPIRED,

    UEMH_EVENT_UECC_ADD_LC_REQ,
    UEMH_EVENT_MAC_RECONFIG_UE_ENTITY_CNF,
    UEMH_EVENT_RLC_RECONFIG_UE_ENTITY_CNF,
    UEMH_EVENT_PDCP_RECONFIG_UE_ENTITY_CNF,
    UEMH_EVENT_S1U_RECONFIG_UE_ENTITY_CNF,
    UEMH_EVENT_PHY_RECONFIG_UE_ENTITY_CNF,
    UEMH_EVENT_RECONFIG_UE_TIMER_EXPIRED,

    UEMH_EVENT_UECC_CONFIGURE_SECURITY_REQ,
    UEMH_EVENT_SECURITY_TIMER_EXPIRED,

    UEMH_EVENT_OAMH_CLEANUP_REQ,

    UEMH_EVENT_S1U_ERROR_IND,

    UEMH_EVENT_UECC_MODIFY_LC_REQ,
    UEMH_EVENT_UECC_MODIFY_LC_ROLLBACK_REQ,
    UEMH_EVENT_UECC_ADD_LC_ROLLBACK_REQ,
    UEMH_EVENT_UECC_DELETE_LC_REQ,
    UEMH_EVENT_SUSPEND_UE_ENTITY_TIMER_EXPIRY,/*29*/
    UEMH_EVENT_UECC_SUSPEND_UE_ENTITY_REQ,/*30 */
    UEMH_EVENT_PDCP_SUSPEND_UE_ENTITY_CNF,/*31 */
    UEMH_EVENT_MAC_RESET_UE_ENTITY_CNF, /*32 */


/*REL 1.2:HANDOVER PROCEDURE START*/
    UEMH_EVENT_UECC_SN_HFN_STATUS_REQ,
    UEMH_EVENT_UECC_SN_HFN_STATUS_IND,
    UEMH_EVENT_UECC_MAC_I_REQ,
    UEMH_EVENT_UECC_DATA_BUFFER_STOP_IND,
    UEMH_EVENT_UECC_UE_INACTIVE_TIME_REQ,
    UEMH_EVENT_UECC_HO_RACH_RESOURCE_REQ,
    UEMH_EVENT_MAC_HO_RACH_RESOURCE_RESP,
    UEMH_EVENT_UECC_HO_REL_RACH_RESOURCE_IND,
    UEMH_EVENT_UECC_RE_ESTABLISH_UE_ENTITY_REQ,
    UEMH_EVENT_UECC_S1U_RECONFIG_UE_ENTITY_REQ,
/*REL 1.2:HANDOVER PROCEDURE START*/
/*JANEN_START*/
    UEMH_EVENT_PDCP_MAC_I_RESP,
    /*SPR_19066_START*/ 
    UEMH_EVENT_MAC_UE_INACTIVE_TIME_RESP,/*This Event has been deleted*/
    /*SPR_19066_END*/
    UEMH_EVENT_PDCP_SN_HFN_STATUS_RESP,
    UEMH_EVENT_S1U_END_MARKER_IND,
/*REL 3.0:UE CONN REESTABLISHMENT START */
    UEMH_EVENT_UECC_REESTABLISHMENT_UE_ENTITY_REQ,
    UEMH_EVENT_RLC_REESTABLISH_UE_ENTITY_CNF,
    UEMH_EVENT_PDCP_REESTABLISH_UE_ENTITY_CNF,
    UEMH_EVENT_UECC_RECONFIG_SECURITY_UE_ENTITY_REQ,
    UEMH_EVENT_UECC_RESUME_UE_ENTITY_REQ,
    UEMH_EVENT_PDCP_RESUME_UE_ENTITY_CNF,
    UEMH_EVENT_REESTABLISH_UE_TIMER_EXPIRED,
    UEMH_EVENT_RECONFIG_SECURITY_UE_TIMER_EXPIRED,
    UEMH_EVENT_PDCP_RESUME_UE_TIMER_EXPIRED,
    UEMH_EVENT_UECC_CHANGE_CRNTI_REQ,
    UEMH_EVENT_PHY_CHANGE_CRNTI_CNF,
    UEMH_EVENT_MAC_CHANGE_CRNTI_CNF,
    UEMH_EVENT_RLC_CHANGE_CRNTI_CNF,
    UEMH_EVENT_PDCP_CHANGE_CRNTI_CNF,
    UEMH_EVENT_CHANGE_CRNTI_TIMER_EXPIRED,
    UEMH_EVENT_UECC_RESET_UE_ENTITY_REQ,
    UEMH_EVENT_UECC_REESTB_UE_ENTITY_COMP_IND,
    /*SPR:6462 start*/
    UEMH_EVENT_UECC_REESTB_UE_ENTITY_COMP_CNF,
    /*SPR:6462 stop*/
/*BUG 604 changes start*/
    UEMH_EVENT_UECC_S1U_INTRA_ENB_DATA_FWD_REQ,
    UEMH_EVENT_UECC_S1U_INTRA_ENB_DATA_FWD_CNF,
    UEMH_EVENT_UECC_S1U_LOCAL_PATH_SWITCH_REQ,
    UEMH_EVENT_UECC_S1U_LOCAL_PATH_SWITCH_CNF,
/*BUG 604 changes stop*/
/*Bug 357 Fix Start*/
    UEMH_EVENT_UECC_PDCP_RE_ESTABLISH_UE_ENTITY_REQ,
/*Bug 357 Fix Stop*/
    /*SPR_19066_START*/
    UEMH_EVENT_PDCP_INACTIVE_UES_IND,
    UEMH_EVENT_PDCP_HO_PREP_INFO_REQ,
    UEMH_EVENT_PDCP_HO_PREP_INFO_RESP,
    /*SPR_19066_END*/
    N_UEMH_EVENTS
} uemh_fsm_event_et;

extern const S8 * UEMH_FSM_STATES_NAMES[];
extern const S8 * UEMH_FSM_EVENTS_NAMES[];

#define RRC_UEMH_FSM_NAME "UEMH_FSM"

#define UEMH_FSM_INIT(p_ue_ctx) \
    do \
    { \
        p_ue_ctx->current_state = UEMH_STATE_IDLE; \
        RRC_LLIM_UE_FSM_INIT_TRACE(p_ue_ctx->ue_index, RRC_UEMH_FSM_NAME, \
            UEMH_FSM_STATES_NAMES[UEMH_STATE_IDLE]); \
    } \
    while (0)

#define UEMH_FSM_GET_CURRENT_STATE(p_ue_ctx)      (p_ue_ctx->current_state)

#define UEMH_FSM_SET_STATE(p_ue_ctx, new_state) \
    do \
    { \
        p_ue_ctx->current_state = new_state; \
        RRC_LLIM_UE_FSM_SET_STATE_TRACE(p_ue_ctx->ue_index, RRC_UEMH_FSM_NAME, \
            UEMH_FSM_STATES_NAMES[new_state]); \
    } \
    while (0)

void uemh_fsm_process_event
(
    uemh_fsm_event_et   event,
    void                *param1,
    void                *param2,
    rrc_llim_ue_ctx_t   *p_ue_ctx,
    rrc_llim_gl_ctx_t   *p_rrc_llim_gl_ctx
);


#endif /* _RRC_LLIM_UEMH_FSM_H_ */

