/******************************************************************************
*
*   FILE NAME:
*       rrc_uemh_fsm_states.h
*
*   DESCRIPTION:
*       This header file contains states of UEMH FSM
*
*   DATE            AUTHOR      REFERENCE       REASON
*   19 May 2009     VasylS      ---------       Initial
*
*   Copyright (c) 2009, Aricent Inc. All Rights Reserved
*
******************************************************************************/

#ifndef _RRC_UEMH_FSM_STATES_H_
#define _RRC_UEMH_FSM_STATES_H_

/* keep in sync with uemh_fsm_tbl! */
typedef enum
{
    UEMH_STATE_IDLE,

    UEMH_STATE_W_FOR_PHY_CREATE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_MAC_CREATE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_RLC_CREATE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PDCP_CREATE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_S1U_CREATE_UE_ENTITY_CNF,

    UEMH_STATE_UE_ENTITY_IN_SERVICE,

    UEMH_STATE_W_FOR_DEL_ALL_UE_ENTITY_CNF,

    UEMH_STATE_W_FOR_CONFIGURE_SECURITY_CNF,

    UEMH_STATE_W_FOR_MAC_RECONFIG_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_RLC_RECONFIG_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PDCP_RECONFIG_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_S1U_RECONFIG_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PHY_RECONFIG_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_DEL_ALL_LC_CNF,
    UEMH_STATE_LLIM_LL_MODIFY_LC_IN_SYNC_ONGOING, 
    UEMH_STATE_LLIM_LL_ADD_LC_IN_SYNC_ONGOING,
    UEMH_STATE_W_FOR_PDCP_SUSPEND_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_MAC_RESET_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_RLC_REESTABLISH_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PDCP_REESTABLISH_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_RECONFIG_SECURITY_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PDCP_RESUME_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PHY_CHANGE_CRNTI_CNF,
    UEMH_STATE_W_FOR_MAC_CHANGE_CRNTI_CNF,
    UEMH_STATE_W_FOR_RLC_CHANGE_CRNTI_CNF,
    UEMH_STATE_W_FOR_PDCP_CHANGE_CRNTI_CNF,
/*SPR_14411_fix Start */
    UEMH_STATE_W_FOR_PDCP_DELETE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_RLC_DELETE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_MAC_DELETE_UE_ENTITY_CNF,
    UEMH_STATE_W_FOR_PHY_DELETE_UE_ENTITY_CNF,
/*SPR_14411_fix Stop */
    N_UEMH_STATES
} uemh_fsm_state_et;



#endif /* _RRC_UEMH_FSM_STATES_H_ */

