/***********************************************************************
**  FUNCTION:
**      Definitions for stats related types and prototypes
************************************************************************
**
**  FILE NAME:
**      egtpu_stat.h
**
**  DATE           NAME               REFERENCE        REASON
**  ----           ----               ---------        ------
**  Oct,2009       Vipul Aggarwal                    Original
**
**   Copyright (C) 2009 Aricent Inc . All Rights Reserved
***********************************************************************/

#ifndef _EGTPU_STAT_DECL_
#define _EGTPU_STAT_DECL_

#ifdef EGTPU_ENABLE_STATS

#define EGTPU_STAT_BASE                         0

#define EGTPU_STAT_IN_API_BASE                  EGTPU_STAT_BASE
#define EGTPU_STATS_API_UNITDATA_IND            (EGTPU_STAT_IN_API_BASE + 0)
#define EGTPU_STATS_API_DATA_REQ                (EGTPU_STAT_IN_API_BASE + 1)
#define EGTPU_STATS_API_RELOC_DATA_REQ          (EGTPU_STAT_IN_API_BASE + 2)
#define EGTPU_STATS_API_SETUP_SAP_REQ           (EGTPU_STAT_IN_API_BASE + 3)
#define EGTPU_STATS_API_RELEASE_SAP_REQ         (EGTPU_STAT_IN_API_BASE + 4)
#define EGTPU_STATS_API_INITDB_REQ              (EGTPU_STAT_IN_API_BASE + 5)
#define EGTPU_STATS_API_SET_TIMER_REQ           (EGTPU_STAT_IN_API_BASE + 6)
#define EGTPU_STATS_API_GET_TIMER_REQ           (EGTPU_STAT_IN_API_BASE + 7)
#define EGTPU_STATS_API_GET_MAX_RETRIES_REQ     (EGTPU_STAT_IN_API_BASE + 8)
#define EGTPU_STATS_API_SET_MAX_RETRIES_REQ     (EGTPU_STAT_IN_API_BASE + 9)
#define EGTPU_STATS_API_GET_STATS_REQ           (EGTPU_STAT_IN_API_BASE + 10)
#define EGTPU_STATS_API_GET_INIT_STATS_REQ      (EGTPU_STAT_IN_API_BASE + 11)
#define EGTPU_STATS_API_INIT_TRACE_LEVEL_REQ    (EGTPU_STAT_IN_API_BASE + 12)
#define EGTPU_STATS_API_SET_TRACE_LEVEL_REQ     (EGTPU_STAT_IN_API_BASE + 13)
#define EGTPU_STATS_API_GET_TRACE_LEVEL_REQ     (EGTPU_STAT_IN_API_BASE + 14)
#define EGTPU_STATS_API_GET_CTXT_INFO_REQ       (EGTPU_STAT_IN_API_BASE + 15)

#ifdef ENDC_ENABLED
#define EGTPU_STATS_X2U_DELIVERY_STATUS         (EGTPU_STAT_IN_API_BASE + 16)
#define EGTPU_STATS_API_LAST_IN_API              EGTPU_STATS_X2U_DELIVERY_STATUS
#else
#define EGTPU_STATS_API_LAST_IN_API           EGTPU_STATS_API_GET_CTXT_INFO_REQ
#endif

#define EGTPU_STAT_OUT_API_BASE               (EGTPU_STATS_API_LAST_IN_API + 1)
#define EGTPU_STATS_API_UDP_UNITDATA_REQ        (EGTPU_STAT_OUT_API_BASE + 0)
#define EGTPU_STATS_API_RELAY_DATA_IND          (EGTPU_STAT_OUT_API_BASE + 1)
#define EGTPU_STATS_API_CP_SETUP_SAP_CNF        (EGTPU_STAT_OUT_API_BASE + 2)
#define EGTPU_STATS_API_CP_RELEASE_SAP_CNF      (EGTPU_STAT_OUT_API_BASE + 3)
#define EGTPU_STATS_API_CP_ERROR_IND            (EGTPU_STAT_OUT_API_BASE + 4)
#define EGTPU_STATS_API_CP_PATH_FAILURE_IND     (EGTPU_STAT_OUT_API_BASE + 5)
#define EGTPU_STATS_API_CP_END_MARKER_IND       (EGTPU_STAT_OUT_API_BASE + 6)
#define EGTPU_STATS_API_LM_INITDB_CNF           (EGTPU_STAT_OUT_API_BASE + 7)
#define EGTPU_STATS_API_LM_SET_TIMER_CNF        (EGTPU_STAT_OUT_API_BASE + 8)
#define EGTPU_STATS_API_LM_GET_TIMER_CNF        (EGTPU_STAT_OUT_API_BASE + 9)
#define EGTPU_STATS_API_LM_GET_MAX_RETRIES_CNF  (EGTPU_STAT_OUT_API_BASE + 10)
#define EGTPU_STATS_API_LM_SET_MAX_RETRIES_CNF  (EGTPU_STAT_OUT_API_BASE + 11)
#define EGTPU_STATS_API_LM_GET_STATS_CNF        (EGTPU_STAT_OUT_API_BASE + 12)
#define EGTPU_STATS_API_LM_GET_INIT_STATS_CNF   (EGTPU_STAT_OUT_API_BASE + 13)
#define EGTPU_STATS_API_LM_INIT_TRACE_LEVEL_CNF (EGTPU_STAT_OUT_API_BASE + 14)
#define EGTPU_STATS_API_LM_SET_TRACE_LEVEL_CNF  (EGTPU_STAT_OUT_API_BASE + 15)
#define EGTPU_STATS_API_LM_GET_TRACE_LEVEL_CNF  (EGTPU_STAT_OUT_API_BASE + 16)
#define EGTPU_STATS_API_LM_GET_CTXT_INFO_CNF    (EGTPU_STAT_OUT_API_BASE + 17)
#define EGTPU_STATS_API_LM_ALARM_NOTIFICATION   (EGTPU_STAT_OUT_API_BASE + 18)
#define EGTPU_STATS_API_MODIFY_REORDERING_REQ   (EGTPU_STAT_OUT_API_BASE + 19)
#define EGTPU_STATS_API_LM_MODIFY_REORDERING_CNF (EGTPU_STAT_OUT_API_BASE + 20)
/*+SPR #3456 */
#define EGTPU_STATS_API_CP_PATH_SUCCESS_IND     (EGTPU_STAT_OUT_API_BASE + 21)
#define EGTPU_STAT_LAST_OUT_API        EGTPU_STATS_API_CP_PATH_SUCCESS_IND
/*-SPR #3456 */

#define EGTPU_STAT_ERROR_BASE                   (EGTPU_STAT_LAST_OUT_API + 1)
#define EGTPU_STAT_STATIC_MEMGET_FAIL           (EGTPU_STAT_ERROR_BASE + 0)
#define EGTPU_STAT_DYNAMIC_MEMGET_FAIL          (EGTPU_STAT_ERROR_BASE + 1)
/*reordering*/
#define EGTPU_STAT_HASH_CTXT_MEMGET_FAIL		(EGTPU_STAT_ERROR_BASE + 2)	
#define EGTPU_STAT_INSERT_DB_FAIL               (EGTPU_STAT_ERROR_BASE + 3)
#define EGTPU_STAT_INSERT_HASH_TBL_FAILURE	   (EGTPU_STAT_ERROR_BASE + 4)	
#define EGTPU_STAT_KEY_NOT_PRESENT              (EGTPU_STAT_ERROR_BASE + 5)
#define EGTPU_STAT_SEND_FAIL                    (EGTPU_STAT_ERROR_BASE + 6)
#define EGTPU_STAT_START_TIMER_FAIL             (EGTPU_STAT_ERROR_BASE + 7)
#define EGTPU_STAT_PDU_DISCARDED                 (EGTPU_STAT_ERROR_BASE + 8)
#define EGTPU_STAT_TIMER_CTXT_MEMGET_FAIL        (EGTPU_STAT_ERROR_BASE + 9)
#define EGTPU_STAT_LAST_ERROR              (EGTPU_STAT_TIMER_CTXT_MEMGET_FAIL)

#define EGTPU_STAT_PMSG_BASE                    (EGTPU_STAT_LAST_ERROR + 1)
#define EGTPU_STAT_ECHO_REQ_MSG_RECEIVED        (EGTPU_STAT_PMSG_BASE + 0)
#define EGTPU_STAT_ECHO_REQ_MSG_SENT            (EGTPU_STAT_PMSG_BASE + 1)
#define EGTPU_STAT_ECHO_RES_MSG_RECEIVED        (EGTPU_STAT_PMSG_BASE + 2)
#define EGTPU_STAT_ECHO_RES_MSG_SENT            (EGTPU_STAT_PMSG_BASE + 3)
#define EGTPU_STAT_SUPP_EXT_HDR_NOTI_MSG_RCVD   (EGTPU_STAT_PMSG_BASE + 4)
#define EGTPU_STAT_SUPP_EXT_HDR_NOTI_MSG_SENT   (EGTPU_STAT_PMSG_BASE + 5)
#define EGTPU_STAT_ERROR_IND_MSG_RECEIVED       (EGTPU_STAT_PMSG_BASE + 6)  
#define EGTPU_STAT_ERROR_IND_MSG_SENT           (EGTPU_STAT_PMSG_BASE + 7)
#define EGTPU_STAT_PDU_RECEIVED                 (EGTPU_STAT_PMSG_BASE + 8)
#define EGTPU_STAT_PDU_SENT                     (EGTPU_STAT_PMSG_BASE + 9)
#define EGTPU_STAT_END_MARKER_MSG_RECEIVED      (EGTPU_STAT_PMSG_BASE + 10)  
#define EGTPU_STAT_END_MARKER_MSG_SENT          (EGTPU_STAT_PMSG_BASE + 11)
#define EGTPU_STAT_LAST_PMSG                 EGTPU_STAT_END_MARKER_MSG_SENT

#define EGTPU_STAT_ERR_PMSG_BASE          	 	(EGTPU_STAT_LAST_PMSG + 1)
#define EGTPU_STAT_ERR_GTP_MESSAGE_TOO_SHORT   	(EGTPU_STAT_ERR_PMSG_BASE + 0)
#define EGTPU_STAT_ERR_UNKNOWN_GTP_SIGNALLING_MESSAGE \
											(EGTPU_STAT_ERR_PMSG_BASE + 1)
#define EGTPU_STAT_ERR_UNEXPECTED_GTP_SIGNALLING_MESSAGE \
											(EGTPU_STAT_ERR_PMSG_BASE + 2)
#define EGTPU_STAT_LAST_ERRONEOUS_PMSG_BASE	\
							EGTPU_STAT_ERR_UNEXPECTED_GTP_SIGNALLING_MESSAGE	


#define EGTPU_STAT_INTERNAL_BASE     (EGTPU_STAT_LAST_ERRONEOUS_PMSG_BASE + 1)
#define EGTPU_STAT_ECHO_TIMER_EXPIRY          (EGTPU_STAT_INTERNAL_BASE + 0)
#define EGTPU_STAT_LAST_INTERNAL               EGTPU_STAT_ECHO_TIMER_EXPIRY


#define EGTPU_MAX_STATS (EGTPU_STAT_LAST_INTERNAL - EGTPU_STAT_BASE + 1)
/* Macro for updating the stats of GTPU */
#define EGTPU_UPDATE_STATS(p_global,type) \
		(p_global->egtpu_stats_arr[type - EGTPU_STAT_BASE]++)
#else

#define EGTPU_UPDATE_STATS(p_global,stats_type)

#endif

#endif
