/******************************************************************************
 *   FILE NAME    : oam_enb_mib_traps.c
 *
 *   DESCRIPTION  : SNMP Agent trap  objects handling code
 *
 *
 ******************************************************************************/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <oam_enb_mib_traps.h>
#include <oam_fm_alarm_defs.h>
#include <alarm.h>
#include <oam_snmp_interface.h>

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;



typedef struct __snmp_oam_if_trap_tbl_t {
    UInt16 trap_id;
    oid trap_oid[SNMP_OAM_IF_TRAP_OID_MAX_LEN];
    size_t oid_len;
} snmp_oam_if_trap_tbl_t;



static snmp_oam_if_trap_tbl_t snmp_oam_if_trap_tbl[] = {
    {
        RRC_PROVISIONING_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 1 },
        14
    },
    {
        S1AP_PROVISIONING_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 2 },
        14
    },
    {
        CRITICAL_CONFIGURATION_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 3 },
        14
    },
    {
        TIMER_START_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 4 },
        14
    },
    {
        TIMER_STOP_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 5 },
        14
    },
    {
        SEND_MSG_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 6 },
        14
    },
    {
        RECV_MSG_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 7 },
        14
    },
    {
        MEM_ALLOC_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 8 },
        14
    },
    {
        MEM_FREE_FAILED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 9 },
        14
    },
    {
        PM_DATA_UPLOAD_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 10 },
        14
    },
    {
        CONFIG_FILE_PERSISTENCE_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 11 },
        14
    },
    {
        IMAGE_DOWNLOAD_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 12 },
        14
    },
    {
        LOG_ARCHIVE_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 13 },
        14
    },
    {
        ARCHIVED_LOG_UPLOAD_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 14 },
        14
    },
    {
        OAM_PKG_INTEGRITY_CHECK_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 15 },
        14
    },
    {
        OAM_PDCP_SECURITY_ENGINE_ERROR_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 16 },
        14
    },
    {
        OAM_LAYER_STARTUP_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 17 },
        14
    },
    {
        HM_RESPONSE_NOT_RECVD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 18 },
        14
    },

    {
        MAC_PHY_OAM_ERR_MSG_INVALID_STATE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 19 },
        14
    },
    {
        MAC_PHY_OAM_ERR_SFN_OUT_OF_SYNC_BY_MORE_THAN_THRESHOLD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 20 },
        14
    },
    {
        MAC_PHY_OAM_ERR_MSG_BCH_MISSING_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 21 },
        14
    },
    {
        MAC_PHY_OAM_ERR_MSG_HI_ERR_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 22 },
        14
    },
    {
        OAM_SON_PCI_CONFLICT_NOTIFICATION,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 23 },
        14
    },
    {
        OAM_SON_PCI_CONFUSION_NOTIFICATION,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 24 },
        14
    },
    /* EMBMS Changes Start */
    {
        M2AP_PROVISIONING_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 25 },
        14
    },
    {
        EMBMS_NOT_SUPPORTED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 26 },
        14
    },
    /* EMBMS Changes End*/

    {
        ABS_PATTERN_NOT_FOUND_FOR_LOW_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 25 },
        14
    },
    {
        ABS_PATTERN_NOT_FOUND_FOR_MID_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 26 },
        14
    },
    {
        ABS_PATTERN_NOT_FOUND_FOR_HIGH_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 27 },
        14
    },
    {
        ABS_PATTERN_NOT_FOUND_FOR_OVER_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 28 },
        14
    },
    {
        ABS_PATTERN_FOUND_FOR_LOW_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 29 },
        14
    },
    {
        ABS_PATTERN_FOUND_FOR_MID_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 30 },
        14
    },
    {
        ABS_PATTERN_FOUND_FOR_HIGH_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 31 },
        14
    },
    {
        ABS_PATTERN_FOUND_FOR_OVER_LOAD_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 1, 32 },
        14
    },
    {
        RRC_SCTP_ASSOCIATION_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 1 },
        14
    },
    {
        RRC_SCTP_ASSOCIATION_RECOVERY_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 2 },
        14
    },
    {
        RRC_S1AP_CONNECTION_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 3 },
        14
    },
    {
        RRC_S1AP_CONNECTION_SUCCESS_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 4 },
        14
    },
    {
        OAM_X2_LINK_UP_IND_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 5 },
        14
    },
    {
        OAM_X2_LINK_DOWN_IND_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 6 },
        14
    },
    {
        EGTPU_S1U_LINK_DOWN_IND_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 7 },
        14
    },
    {
        EGTPU_S1U_LINK_UP_IND_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 8 },
        14
    },
    /* EMBMS Changes Start */
    {
        M2AP_SCTP_ASSOC_FAIL_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 9 },
        14
    },
    {
        RRC_M2AP_CONNECTION_SUCC_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 10 },
        14
    },
    {
        RRC_M2AP_CONNECTION_FAIL_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 11 },
        14
    },
    {
        M2AP_PROVISIONING_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 12 },
        14
    },
    {
        EMBMS_NOT_SUPPORTED_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 13 },
        14
    },

    {
        S1AP_RESET_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 9 },
        14
    },
    {
        CRITICAL_CONFIGURATION_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 10 },
        14
    },
    {
        X2AP_PEER_ENB_RESET_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 11 },
        14
    },
    {
        X2AP_SELF_RESET_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 12 },
        14
    },
    {
        RRC_X2AP_CONNECTION_FAILURE_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 13 },
        14
    },
    {
        RRC_X2AP_CONNECTION_SUCCESS_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 14 },
        14
    },
    {
        RRC_S1AP_ERROR_INDICATION_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 15 },
        14
    },
    {
        RRC_X2AP_ERROR_INDICATION_ALARM_ID,
        { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 2, 2, 16 },
        14
    }
};



#define SNMP_OAM_IF_TRAP_TBL_SIZE (sizeof(snmp_oam_if_trap_tbl) \
        / sizeof(snmp_oam_if_trap_tbl_t))



SInt16 snmp_oam_find_trap_oid(UInt16 trapid)
{
    UInt16 cnt = 0;
    for(cnt = 0; cnt < SNMP_OAM_IF_TRAP_TBL_SIZE; ++cnt) {
        if(trapid == snmp_oam_if_trap_tbl[cnt].trap_id) {
            return cnt;
        }
    }

    return -1;
}



SInt32 snmp_oam_send_snmp_trap(snmp_oam_trap_param_t *trap_obj)
{
    netsnmp_variable_list *var_list = NULL;
    UInt16 trapid = 0;
    SInt16 trap_tbl_idx = 0;
    const oid       trapIdentifier_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 1, 0 };
    const oid       trapEventTime_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 2, 0 };
    const oid       trapNotificationType_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 3, 0 };
    const oid       trapManagedObjectInstance_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 4, 0 };
    const oid       trapEventType_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 5, 0 };
    const oid       trapProbableCause_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 6, 0 };
    const oid       trapSpecificProblem_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 7, 0 };
    const oid       trapPerceivedSeverity_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 8, 0 };
    const oid       trapAdditionalText_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 9, 0 };
    const oid       trapAdditionalInformation_oid[] =
    { 1, 3, 6, 1, 4, 1, 29601, 11, 20, 2, 1, 1, 10, 0 };

    trapid = oam_snmp_atoi(trap_obj->trap_id);
    trap_tbl_idx = snmp_oam_find_trap_oid(trapid);

    if(-1 == trap_tbl_idx) {
        OAM_SNMP_LOG(SNMP, OAM_SNMP_WARNING,
                     "Unsupported trapID[%u] received from OAM", trapid);
        return SNMP_ERR_BADVALUE;
    }

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
            snmptrap_oid, snmptrap_oid_len,
            ASN_OBJECT_ID,
            snmp_oam_if_trap_tbl[trap_tbl_idx].trap_oid,
            snmp_oam_if_trap_tbl[trap_tbl_idx].oid_len);

    /*
     * Add any objects from the trap definition
     */

    /* Add trap-identifier to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapIdentifier_oid,
            OID_LENGTH(trapIdentifier_oid),
            ASN_OCTET_STR,
            trap_obj->trap_id,
            oam_snmp_strlen(trap_obj->trap_id) + 1);

    /* Add trap-raised-time to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapEventTime_oid,
            OID_LENGTH(trapEventTime_oid),
            ASN_OCTET_STR,
            trap_obj->event_time,
            oam_snmp_strlen(trap_obj->event_time) + 1);

    /* Add trap-changed-time to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapNotificationType_oid,
            OID_LENGTH(trapNotificationType_oid),
            ASN_OCTET_STR,
            trap_obj->notif_type,
            oam_snmp_strlen(trap_obj->notif_type) + 1);

    /* Add trap-managed-object-instance to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapManagedObjectInstance_oid,
            OID_LENGTH(trapManagedObjectInstance_oid),
            ASN_OCTET_STR,
            trap_obj->managed_obj_inst,
            oam_snmp_strlen(trap_obj->managed_obj_inst) + 1);

    /* Add trap-event-type to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapEventType_oid,
            OID_LENGTH(trapEventType_oid),
            ASN_OCTET_STR,
            trap_obj->event_type,
            oam_snmp_strlen(trap_obj->event_type) + 1);

    /* Add trap-probable-cause to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapProbableCause_oid,
            OID_LENGTH(trapProbableCause_oid),
            ASN_OCTET_STR,
            trap_obj->prob_cause,
            oam_snmp_strlen(trap_obj->prob_cause) + 1);

    /* Add trap-specific-problem to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapSpecificProblem_oid,
            OID_LENGTH(trapSpecificProblem_oid),
            ASN_OCTET_STR,
            trap_obj->spec_problem,
            oam_snmp_strlen(trap_obj->spec_problem) + 1);

    /* Add trap-perceived-severity to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapPerceivedSeverity_oid,
            OID_LENGTH(trapPerceivedSeverity_oid),
            ASN_OCTET_STR,
            trap_obj->perceived_sev,
            oam_snmp_strlen(trap_obj->perceived_sev) + 1);

    /* Add trap-additional-text to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapAdditionalText_oid,
            OID_LENGTH(trapAdditionalText_oid),
            ASN_OCTET_STR,
            trap_obj->add_text,
            oam_snmp_strlen(trap_obj->add_text) + 1);

    /* Add trap-additional-info to variable bindings */
    snmp_varlist_add_variable(&var_list,
            trapAdditionalInformation_oid,
            OID_LENGTH(trapAdditionalInformation_oid),
            ASN_OCTET_STR,
            trap_obj->add_info,
            oam_snmp_strlen(trap_obj->add_info) + 1);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */

    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}

