/****************************************************************************
 *
 *  ARICENT -
 *
 *  Copyright (C) 2009 Aricent Inc. All Rights Reserved.
 *
 ****************************************************************************
 *
 *  $Id: rohc_stats_def.h,v 1.1.1.1 2010/02/11 04:51:26 cm_intel Exp $
 *
 ****************************************************************************
 *
 *  File Description : This file contains the statistics to be used by various
 *                     ROHC modules.
 *
 ****************************************************************************
 *
 * Revision Details
 * ----------------
 *
 * $Log: rohc_stats_def.h,v $
 * Revision 1.1.1.1  2010/02/11 04:51:26  cm_intel
 * eNB framework for intel
 *
 * Revision 1.4.2.1  2009/06/09 11:34:56  gur19140
 * first wave of Integration
 *
 * Revision 1.4  2009/05/28 04:41:36  gur19836
 * File Header updated
 *
 *
 *
 ****************************************************************************/

#ifndef _ROHC_STATS_DEF_H_
#define _ROHC_STATS_DEF_H_

#define ROHC_STATS_BASE             0

/* API Stats */
#define ROHC_STATS_API_BASE                     (ROHC_STATS_BASE)
#define PDCP_ROHC_STATS_API_DATA_REQ            (ROHC_STATS_API_BASE + 0)
#define PDCP_ROHC_STATS_CONFIG_REQ              (ROHC_STATS_API_BASE + 1)
#define PDCP_ROHC_STATS_API_RECONFIG_REQ        (ROHC_STATS_API_BASE + 2)
#define PDCP_ROHC_STATS_API_RELEASE_REQ         (ROHC_STATS_API_BASE + 3)
#define PDCP_ROHC_STATS_API_PACKET_SIZE_USED_REQ        (ROHC_STATS_API_BASE + 4)
#define PDCP_ROHC_STATS_API_CONTEXT_REQ         (ROHC_STATS_API_BASE + 5)
#define PDCP_ROHC_STATS_API_SET_ROHC_INFO_REQ       (ROHC_STATS_API_BASE + 6)
#define PDCP_ROHC_STATS_RLC_API_DATA_IND        (ROHC_STATS_API_BASE + 7)


#define PDCP_ROHC_STATS_API_RLC_DATA_REQ        (ROHC_STATS_API_BASE + 8)
#define PDCP_ROHC_STATS_API_CONFIG_RESP         (ROHC_STATS_API_BASE + 9)
#define PDCP_ROHC_STATS_API_RECONFIG_RESP       (ROHC_STATS_API_BASE + 10)
#define PDCP_ROHC_STATS_API_RELEASE_RESP        (ROHC_STATS_API_BASE + 11)
#define PDCP_ROHC_STATS_API_PACKET_SIZE_USED_RESP       (ROHC_STATS_API_BASE + 12)
#define PDCP_ROHC_STATS_API_CONTEXT_CONF        (ROHC_STATS_API_BASE + 13)
#define PDCP_ROHC_STATS_API_SET_ROHC_INFO_RESP      (ROHC_STATS_API_BASE + 14)
#define PDCP_ROHC_STATS_API_PDCP_DATA_IND       (ROHC_STATS_API_BASE + 15)

#define ROHC_STATS_API_LAST                     (PDCP_ROHC_STATS_API_PDCP_DATA_IND)


/* System Error Stats. */
#define ROHC_STATS_ERROR_BASE               (ROHC_STATS_API_LAST + 1)
#define PDCP_ROHC_STATS_ERR_MEMGET_FAIL     (ROHC_STATS_ERROR_BASE + 0)
#define PDCP_ROHC_STATS_ERR_MEMFREE_FAIL    (ROHC_STATS_ERROR_BASE + 1)
#define ROHC_STATS_ERROR_LAST               (PDCP_ROHC_STATS_ERR_MEMFREE_FAIL)

/* Internal Stats. */
#define ROHC_STATS_INTERNAL_BASE            (ROHC_STATS_ERROR_LAST+100)

#define ROHC_TOTAL_NO_OF_APIS_PROCESSED     (ROHC_STATS_ERROR_LAST + 1)
#define ROHC_NO_OF_IR_PROCESSED             (ROHC_STATS_INTERNAL_BASE + 0)
#define ROHC_NO_OF_IR_CREATED               (ROHC_STATS_INTERNAL_BASE + 1)
#define ROHC_NO_OF_IR_DYN_PROCESSED         (ROHC_STATS_INTERNAL_BASE + 2)
#define ROHC_NO_OF_IR_DYN_CREATED           (ROHC_STATS_INTERNAL_BASE + 3)
#define ROHC_NO_OF_ACK_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 4)
#define ROHC_NO_OF_ACK_CREATED              (ROHC_STATS_INTERNAL_BASE + 5)
#define ROHC_NO_OF_NACK_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 6)
#define ROHC_NO_OF_NACK_CREATED             (ROHC_STATS_INTERNAL_BASE + 7)
#define ROHC_NO_OF_STATIC_NACK_PROCESSED    (ROHC_STATS_INTERNAL_BASE + 8)
#define ROHC_NO_OF_STATIC_NACK_CREATED      (ROHC_STATS_INTERNAL_BASE + 9)
#define ROHC_NO_OF_R_0_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 10)
#define ROHC_NO_R_0_CRC_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 11)
#define ROHC_NO_UO_0_PROCESSED              (ROHC_STATS_INTERNAL_BASE + 12)
#define ROHC_NO_OF_R_1_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 13)
#define ROHC_NO_R_1_ID_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 14)
#define ROHC_NO_R_1_TS_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 15)
#define ROHC_NO_OF_UO_1_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 16)
#define ROHC_NO_UO_1_ID_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 17)
#define ROHC_NO_UO_1_TS_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 18)
#define ROHC_NO_OF_UOR_2_PROCESSED          (ROHC_STATS_INTERNAL_BASE + 19)
#define ROHC_NO_UOR_2_ID_PROCESSED          (ROHC_STATS_INTERNAL_BASE + 20)
#define ROHC_NO_UOR_2_TS_PROCESSED          (ROHC_STATS_INTERNAL_BASE + 21)
#define ROHC_NO_OF_R_0_CREATED              (ROHC_STATS_INTERNAL_BASE + 22)
#define ROHC_NO_R_0_CRC_CREATED             (ROHC_STATS_INTERNAL_BASE + 23)
#define ROHC_NO_UO_0_CREATED                (ROHC_STATS_INTERNAL_BASE + 24)
#define ROHC_NO_OF_R_1_CREATED              (ROHC_STATS_INTERNAL_BASE + 25)
#define ROHC_NO_R_1_ID_CREATED              (ROHC_STATS_INTERNAL_BASE + 26)
#define ROHC_NO_R_1_TS_CREATED              (ROHC_STATS_INTERNAL_BASE + 27)
#define ROHC_NO_OF_UO_1_CREATED             (ROHC_STATS_INTERNAL_BASE + 28)
#define ROHC_NO_UO_1_ID_CREATED             (ROHC_STATS_INTERNAL_BASE + 29)
#define ROHC_NO_UO_1_TS_CREATED             (ROHC_STATS_INTERNAL_BASE + 30)
#define ROHC_NO_OF_UOR_2_CREATED            (ROHC_STATS_INTERNAL_BASE + 31)
#define ROHC_NO_UOR_2_ID_CREATED            (ROHC_STATS_INTERNAL_BASE + 32)
#define ROHC_NO_UOR_2_TS_CREATED            (ROHC_STATS_INTERNAL_BASE + 33)
#define ROHC_NO_OF_MODE_TRANS_U_TO_O_INIT        (ROHC_STATS_INTERNAL_BASE + 34)
#define ROHC_NO_OF_MODE_TRANS_U_TO_R_INIT        (ROHC_STATS_INTERNAL_BASE + 35)
#define ROHC_NO_OF_MODE_TRANS_O_TO_R_INIT        (ROHC_STATS_INTERNAL_BASE + 36)
#define ROHC_NO_OF_MODE_TRANS_O_TO_U_INIT        (ROHC_STATS_INTERNAL_BASE + 37)
#define ROHC_NO_OF_MODE_TRANS_R_TO_U_INIT        (ROHC_STATS_INTERNAL_BASE + 38)
#define ROHC_NO_OF_MODE_TRANS_R_TO_O_INIT        (ROHC_STATS_INTERNAL_BASE + 39)
#define ROHC_NO_OF_TIMES_PEDCM_INVK         (ROHC_STATS_INTERNAL_BASE + 40)
#define ROHC_NO_OF_TIMES_CRC_FAILED         (ROHC_STATS_INTERNAL_BASE + 41)
#define ROHC_NO_OF_PKT_REJECTED             (ROHC_STATS_INTERNAL_BASE + 42)
#define ROHC_LIST_ENC_NO_GEN_SCHM_USED_PROCESSED            (ROHC_STATS_INTERNAL_BASE + 43)
#define ROHC_LIST_ENC_NO_INS_ONLY_SCHM_USED_PROCESSED       (ROHC_STATS_INTERNAL_BASE + 44)
#define ROHC_LIST_ENC_NO_REM_ONLY_SCHM_USED_PROCESSED       (ROHC_STATS_INTERNAL_BASE + 45)
#define ROHC_LIST_ENC_NO_REM_THEN_INS_SCHM_USED_PROCESSED   (ROHC_STATS_INTERNAL_BASE + 46)
#define ROHC_LIST_ENC_NO_GEN_SCHM_USED_CREATED              (ROHC_STATS_INTERNAL_BASE + 47)
#define ROHC_LIST_ENC_NO_INS_ONLY_SCHM_USED_CREATED         (ROHC_STATS_INTERNAL_BASE + 48)
#define ROHC_LIST_ENC_NO_REM_ONLY_SCHM_USED_CREATED         (ROHC_STATS_INTERNAL_BASE + 49)
#define ROHC_LIST_ENC_NO_REM_THEN_INS_SCHM_USED_CREATED     (ROHC_STATS_INTERNAL_BASE + 50)

#define ROHC_NO_OF_MODE_TRANS_U_TO_O_RCVD        (ROHC_STATS_INTERNAL_BASE + 51)
#define ROHC_NO_OF_MODE_TRANS_U_TO_R_RCVD        (ROHC_STATS_INTERNAL_BASE + 52)
#define ROHC_NO_OF_MODE_TRANS_O_TO_R_RCVD        (ROHC_STATS_INTERNAL_BASE + 53)
#define ROHC_NO_OF_MODE_TRANS_O_TO_U_RCVD        (ROHC_STATS_INTERNAL_BASE + 54)
#define ROHC_NO_OF_MODE_TRANS_R_TO_U_RCVD        (ROHC_STATS_INTERNAL_BASE + 55)
#define ROHC_NO_OF_MODE_TRANS_R_TO_O_RCVD        (ROHC_STATS_INTERNAL_BASE + 56)

#define ROHC_NO_OF_NORMALP0_CREATED            (ROHC_STATS_INTERNAL_BASE + 57)
#define ROHC_NO_OF_NORMALP0_PROCESSED          (ROHC_STATS_INTERNAL_BASE + 58)

/* Internal STATS for Profile 6 packet types */

#define ROHC_NO_OF_IR_CR_P6_CREATED            (ROHC_STATS_INTERNAL_BASE + 59)
#define ROHC_NO_OF_IR_CR_P6_PROCESSED          (ROHC_STATS_INTERNAL_BASE + 60)
#define ROHC_NO_OF_CO_P6_CREATED               (ROHC_STATS_INTERNAL_BASE + 61)
#define ROHC_NO_OF_CO_P6_PROCESSED             (ROHC_STATS_INTERNAL_BASE + 62)
#define ROHC_NO_OF_RND1_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 63)
#define ROHC_NO_OF_RND1_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 64)
#define ROHC_NO_OF_RND2_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 65)
#define ROHC_NO_OF_RND2_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 66)
#define ROHC_NO_OF_RND3_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 67)
#define ROHC_NO_OF_RND3_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 68)
#define ROHC_NO_OF_RND4_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 69)
#define ROHC_NO_OF_RND4_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 70)
#define ROHC_NO_OF_RND5_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 71)
#define ROHC_NO_OF_RND5_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 72)
#define ROHC_NO_OF_RND6_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 73)
#define ROHC_NO_OF_RND6_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 74)
#define ROHC_NO_OF_RND7_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 75)
#define ROHC_NO_OF_RND7_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 76)
#define ROHC_NO_OF_RND8_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 77)
#define ROHC_NO_OF_RND8_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 78)
#define ROHC_NO_OF_SEQ1_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 79)
#define ROHC_NO_OF_SEQ1_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 80)
#define ROHC_NO_OF_SEQ2_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 81)
#define ROHC_NO_OF_SEQ2_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 82)
#define ROHC_NO_OF_SEQ3_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 83)
#define ROHC_NO_OF_SEQ3_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 84)
#define ROHC_NO_OF_SEQ4_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 85)
#define ROHC_NO_OF_SEQ4_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 86)
#define ROHC_NO_OF_SEQ5_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 87)
#define ROHC_NO_OF_SEQ5_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 88)
#define ROHC_NO_OF_SEQ6_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 89)
#define ROHC_NO_OF_SEQ6_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 90)
#define ROHC_NO_OF_SEQ7_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 91)
#define ROHC_NO_OF_SEQ7_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 92)
#define ROHC_NO_OF_SEQ8_P6_CREATED             (ROHC_STATS_INTERNAL_BASE + 93)
#define ROHC_NO_OF_SEQ8_P6_PROCESSED           (ROHC_STATS_INTERNAL_BASE + 94)

#define ROHC_STATS_INTERNAL_LAST        (ROHC_NO_OF_SEQ8_P6_PROCESSED)

#define     ROHC_MAX_STATS      (ROHC_STATS_INTERNAL_LAST+1)

#endif /* _ROHC_STATS_DEF_H_ */

